[[main]]
name = "O nas"
url = "about/"
weight = 1

[[main]]
name = "Blog"
url = "blog/"
weight = 2

[[main]]
name = "Kursy"
url = "course/"
weight = 3

[[main]]
name = "Badania"
url = "research/"
weight = 4

[[main]]
name = "Ogłoszenia"
url = "notice/"
weight = 5

[[main]]
name = "Kontakt"
url = "contact/"
weight = 6

[[footer]]
name = "O nas"
url = "about/"

[[footer]]
name = "Blog"
url = "blog/"

[[footer]]
name = "Kursy"
url = "course/"

[[footer]]
name = "Badania"
url = "research/"

[[footer]]
name = "Ogłoszenia"
url = "notice/"

[[footer]]
name = "Kontakt"
url = "contact/"
