[[main]]
name = "O nas"
url = "about/"
weight = 1

[[main]]
name = "Blog"
url = "blog/"
weight = 2

[[main]]
name = "Panel nauki"
url = "course/"
weight = 3

[[main]]
name = "Badania"
url = "research/"
weight = 4

[[main]]
name = "Ogłoszenia"
url = "notice/"
weight = 5

[[main]]
name = "Kontakt"
url = "contact/"
weight = 6

[[main]]
name = "System"
url = "teacher/"
weight = 7

[[main]]
name = "Diagramy"
url = "diagrams/"
weight = 8

[[footer]]
name = "O nas"
url = "about/"

[[footer]]
name = "Blog"
url = "blog/"

[[footer]]
name = "Panel nauki"
url = "course/"

[[footer]]
name = "Badania"
url = "research/"

[[footer]]
name = "System"
url = "teacher/"

[[footer]]
name = "Ogłoszenia"
url = "notice/"

[[footer]]
name = "Diagramy"
url = "diagrams/"

[[footer]]
name = "Kontakt"
url = "contact/"
