canEnforceMinimumPythonVersion = true
condaSolveImplementation = hawk
enableCodeAssistEnvironmentCaching = true
enableLegacyFallback = false
envPackingLogicVersion = 2
org.gradle.caching = true
org.gradle.vfs.watch = false
palantirModelsVersion = 0.2281.0
rootProjectName = acaciafund-pipeline
systemProp.http.connectionTimeout = 600000
systemProp.http.socketTimeout = 600000
systemProp.org.gradle.internal.http.connectionTimeout = 600000
systemProp.org.gradle.internal.http.socketTimeout = 600000
transformsDefaultBranchName = master
transformsLangPythonPluginVersion = 1.1165.0
transformsRepoOrg = TierPalan-96733d
transformsRepoPath = /TierPalan-96733d/Acacia/acaciafund-pipeline
transformsRepoProject = Acacia
transformsRepoRid = ri.stemma.main.repository.5f0e7650-f235-445e-a422-f1977854d32c
transformsVersion = 10.118.0
useCondaLocksForPlatforms = linux-64
useDefaultPython = false
useHawkAsDefaultSolver = true
useHawkUvSolver = true
useIncrementalSolve = true
