"""Tests for redirect rules, _redirects file, and redirects.json."""

import json
import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))


class TestCloudflareRedirects:
    """Tests for the _redirects file generated by build.py."""

    @pytest.fixture(autouse=True)
    def load_redirects(self, dist_dir):
        redirects_path = dist_dir / "_redirects"
        if not redirects_path.exists():
            pytest.skip("_redirects not found")
        self.lines = redirects_path.read_text(encoding="utf-8").strip().splitlines()

    def test_aml_to_compliance_wildcard(self):
        assert any("aml/*" in line and "compliance/:splat" in line and "301" in line
                    for line in self.lines)

    def test_stock_to_markets_wildcard(self):
        assert any("stock/*" in line and "markets/:splat" in line and "301" in line
                    for line in self.lines)

    def test_science_to_research(self):
        assert any("science/*" in line and "data/research/:splat" in line and "301" in line
                    for line in self.lines)

    def test_aml_signals_redirect(self):
        assert any("aml/signals/*" in line and "compliance/signals/:splat" in line
                    for line in self.lines)

    def test_no_self_redirects(self):
        for line in self.lines:
            if line.strip().startswith("#") or not line.strip():
                continue
            parts = line.split()
            if len(parts) >= 2:
                src = parts[0].rstrip("*").rstrip("/")
                dst = parts[1].rstrip(":splat").rstrip("/")
                assert src != dst, f"Self-redirect detected: {line}"


class TestRedirectsJson:
    """Tests for redirects.json consistency."""

    @pytest.fixture(autouse=True)
    def load_redirects(self):
        path = PROJECT_ROOT / "redirects.json"
        if not path.exists():
            pytest.skip("redirects.json not found")
        self.redirects = json.loads(path.read_text(encoding="utf-8"))

    def test_is_dict(self):
        assert isinstance(self.redirects, dict)

    def test_no_empty_keys(self):
        assert all(k for k in self.redirects), "Empty redirect key found"

    def test_no_self_redirects(self):
        for old, new in self.redirects.items():
            assert old != new, f"Self-redirect: {old}"

    def test_redirect_targets_dont_conflict_with_pillar_urls(self):
        """Redirect targets should not map to the old 'aml/' path."""
        for old, new in self.redirects.items():
            if new.startswith("aml/"):
                # Old redirects to aml/ are OK — they'll be caught by _redirects
                pass

    def test_no_circular_redirects(self):
        """No A -> B where B -> A."""
        for old, new in self.redirects.items():
            if new in self.redirects:
                assert self.redirects[new] != old, (
                    f"Circular redirect: {old} -> {new} -> {self.redirects[new]}"
                )


class TestAmlComplianceRedirect:
    """Verify /aml/ path redirects to /compliance/."""

    def test_aml_index_is_redirect(self, dist_dir):
        aml_index = dist_dir / "aml" / "index.html"
        assert aml_index.exists(), "dist/aml/index.html not found"
        content = aml_index.read_text(encoding="utf-8")
        assert "compliance" in content.lower(), "AML redirect page doesn't reference compliance"
        assert "refresh" in content.lower() or "301" in content, "Not a redirect page"
