PILLAR_EXTRA_CONCEPT_SEEDS: list[dict] = [{'aliases': ['acidtransactionmanagement'],
  'category': 'specialized',
  'confidence_score': 0.7,
  'cross_pillar_analogs': ['money-laundering-basics', 'design', 'funding'],
  'description': 'A concept related to acid-transaction-management',
  'epistemic_status': 'instrumental',
  'governance_model': 'distributed',
  'id': 'acid-transaction-management',
  'label': 'Acid Transaction Management',
  'normative_basis': 'utilitarian',
  'ontological_commitment': 'realist',
  'philosophical_lineage': ['positivism', 'systems_theory'],
  'philosophical_sources': [],
  'pillar': 'data-engineering',
  'semantic_contract_type': 'technical',
  'source_inspiration': 'curated',
  'temporal_ontology': 'process_based',
  'uncertainty_class': 'measurable'},
 {'aliases': ['algorithmic systemic risk', 'cascade failure', 'flash crash'],
  'category': 'risk-assessment',
  'confidence_score': 0.85,
  'cross_pillar_analogs': ['market-microstructure', 'aml-risk-scoring', 'algorithmic-trading'],
  'description': 'A failure mode in which correlated automated strategies amplify a shock through feedback loops — '
                 'herd-style models, shared data feeds, and reflexive price reactions — producing flash crashes and '
                 'system-wide stress faster than any human or slow-moving rule can respond. The algorithmic extension '
                 "of Schwarcz's systemic risk.",
  'epistemic_status': 'instrumental',
  'governance_model': 'algorithmic',
  'id': 'algorithmic-cascade',
  'label': 'Algorithmic Cascade',
  'normative_basis': 'utilitarian',
  'ontological_commitment': 'processual',
  'philosophical_lineage': ['systems_theory', 'complexity_theory'],
  'philosophical_sources': ['Schwarcz, Steven L. Systemic Risk (2008)',
                            'Kirilenko, A., et al. The Flash Crash: The Impact of High Frequency Trading (2017)'],
  'pillar': 'cross-pillar',
  'semantic_contract_type': 'descriptive',
  'source_inspiration': 'curated',
  'temporal_ontology': 'event_based',
  'uncertainty_class': 'knightian'},
 {'aliases': ['AML effectiveness',
              'Ferwerda',
              'Levi-Reuter',
              'FATF effectiveness',
              'aml outcomes',
              'aml-effectiveness'],
  'category': 'industry-analysis',
  'confidence_score': 1.0,
  'cross_pillar_analogs': ['model-cards', 'semiconductor-industry'],
  'description': 'AML regime effectiveness research, including Levi and Reuter (2006) and Ferwerda et al. (SSRN), '
                 'critically examines whether anti-money laundering regulations actually achieve their stated goals. '
                 'These studies question the effectiveness-cost trade-off, highlighting that despite massive spending '
                 '($200B+ annually) and millions of SARs, there is limited evidence that AML efforts significantly '
                 'reduce crime.',
  'epistemic_status': 'pragmatic',
  'governance_model': 'network',
  'id': 'aml-effectiveness',
  'label': 'AML Regime Effectiveness',
  'normative_basis': 'utilitarian',
  'ontological_commitment': 'critical_realist',
  'philosophical_lineage': ['skepticism', 'institutional_theory', 'policy_analysis', 'social_epistemology'],
  'philosophical_sources': ["Levi, Michael, and Peter Reuter. 'Money Laundering: A Review.' Crime and Justice (2006)",
                            'Naylor, R.T. Wages of Crime: Black Markets, Illegal Finance, and the Underworld Economy '
                            '(2002)',
                            'Sharman, J.C. The Desperate Quest for Grand Corruption (2020)'],
  'pillar': 'aml',
  'semantic_contract_type': 'evaluative',
  'source_inspiration': "Levi, Michael, and Peter Reuter. 'Money Laundering: A Review of the Economics of Crime.' "
                        "Crime and Justice 34 (2006): 289-375. Ferwerda, Joras, et al. 'Assessing the Effectiveness of "
                        "AML Policies.' SSRN (various).",
  'temporal_ontology': 'processual',
  'uncertainty_class': 'knightian'},
 {'aliases': ['AML program reform 2026',
              'Fed AML proposal',
              'FinCEN program rule',
              'BSA overhaul 2026',
              'effectiveness-based supervision',
              'risk-based resource allocation'],
  'category': 'regulations',
  'confidence_score': 1.0,
  'cross_pillar_analogs': ['data-governance', 'ai-act-high-risk', 'ai-conformity-assessment'],
  'description': 'AML Program Reform covers the 2026 restructuring of US AML compliance requirements. The Federal '
                 "Reserve's July 2026 proposed rule, FinCEN's April 2026 AML/CFT program rule, and the GENIUS Act "
                 'collectively create the most significant BSA overhaul in 20+ years. Key elements include risk-based '
                 "resource allocation, effectiveness-based supervision (only 'significant failures' trigger "
                 'enforcement), board-level program approval, US-based compliance officer requirement, and explicit '
                 'regulatory encouragement of AI/ML adoption for compliance. This represents a paradigm shift from '
                 'prescriptive checklist-based compliance to outcomes-oriented risk management.',
  'epistemic_status': 'regulatory',
  'governance_model': 'hierarchical',
  'id': 'aml-program-reform',
  'label': 'AML Program Reform',
  'normative_basis': 'utilitarian',
  'ontological_commitment': 'constructivist',
  'philosophical_lineage': ['legal_positivism', 'regulatory_theory', 'risk_governance'],
  'philosophical_sources': ["Federal Register. 'Proposed Rule: AML Program Requirements.' July 7, (2026)",
                            "FinCEN. 'Proposed AML/CFT Program Rule.' April (2026)",
                            'GENIUS Act. (2026)'],
  'pillar': 'aml',
  'semantic_contract_type': 'regulatory',
  'source_inspiration': 'Federal Reserve proposed rule on AML program requirements (July 7, 2026); FinCEN proposed '
                        'AML/CFT program rule (April 2026); GENIUS Act (2026)',
  'temporal_ontology': 'process_based',
  'uncertainty_class': 'knightian'},
 {'aliases': ['Black-Scholes-Merton', 'BSM', 'options pricing model', 'black-scholes-1973', 'black-scholes-formula'],
  'category': 'advanced-techniques',
  'confidence_score': 1.0,
  'cross_pillar_analogs': ['aml-model-validation', 'network-analysis', 'cyber-aml'],
  'description': 'The Black-Scholes model provides a closed-form solution for pricing European options, establishing '
                 'the theoretical foundation for modern options markets. It shows that option prices can be derived '
                 'from a no-arbitrage condition using a continuously rebalanced hedge portfolio.',
  'epistemic_status': 'instrumental',
  'governance_model': 'market_based',
  'id': 'black-scholes',
  'label': 'Black-Scholes Options Pricing Model',
  'normative_basis': 'utilitarian',
  'ontological_commitment': 'fictionalist',
  'philosophical_lineage': ['probability_philosophy', 'rational_expectations', 'financial_mathematics'],
  'philosophical_sources': ["Black, Fischer, and Myron Scholes. 'The Pricing of Options and Corporate Liabilities.' "
                            'JPE (1973)',
                            "Merton, Robert C. 'Theory of Rational Option Pricing.' Bell Journal of Economics (1973)",
                            "Bachelier, Louis. 'Theorie de la Speculation.' Annales Scientifiques (1900)"],
  'pillar': 'stock',
  'semantic_contract_type': 'constitutive',
  'source_inspiration': "Black, Fischer, and Myron Scholes. 'The Pricing of Options and Corporate Liabilities.' "
                        "Journal of Political Economy 81, no. 3 (1973): 637-54. Merton, Robert C. 'Theory of Rational "
                        "Option Pricing.' Bell Journal of Economics 4, no. 1 (1973): 141-83.",
  'temporal_ontology': 'event_based',
  'uncertainty_class': 'measurable'},
 {'aliases': ['CAPM', 'Sharpe-Lintner model', 'security market line', 'SML', 'capital-asset-pricing-model'],
  'category': 'foundations',
  'confidence_score': 1.0,
  'cross_pillar_analogs': ['risk-based-approach'],
  'description': 'The Capital Asset Pricing Model (CAPM), developed by Sharpe (1964), Lintner (1965), and Mossin '
                 '(1966), provides a theoretical framework for relating expected return to systematic risk. The key '
                 "insight is that only non-diversifiable (market) risk is priced, and an asset's expected return is "
                 'linearly related to its beta with the market portfolio.',
  'epistemic_status': 'ontological',
  'governance_model': 'market_based',
  'id': 'capital-asset-pricing-model',
  'label': 'Capital Asset Pricing Model (CAPM)',
  'normative_basis': 'utilitarian',
  'ontological_commitment': 'fictionalist',
  'philosophical_lineage': ['probability_philosophy', 'rational_expectations', 'value_theory'],
  'philosophical_sources': ["Sharpe, William F. 'Capital Asset Prices.' Journal of Finance (1964)",
                            "Lintner, John. 'The Valuation of Risk Assets.' Review of Economics and Statistics (1965)",
                            "Markowitz, Harry. 'Portfolio Selection.' Journal of Finance (1952)"],
  'pillar': 'stock',
  'semantic_contract_type': 'constitutive',
  'source_inspiration': "Sharpe, William F. 'Capital Asset Prices: A Theory of Market Equilibrium under Conditions of "
                        "Risk.' Journal of Finance 19, no. 3 (1964): 425-42.",
  'temporal_ontology': 'event_based',
  'uncertainty_class': 'measurable'},
 {'aliases': ['policy as code', 'regulation by design', 'regtech architecture'],
  'category': 'regtech',
  'confidence_score': 0.85,
  'cross_pillar_analogs': ['data-governance', 'aml-data-governance', 'data-contracts'],
  'description': 'The practice of embedding legal and regulatory rules directly into the architecture of data '
                 'pipelines and software systems — versioned rule artifacts, data contracts as legal interfaces, '
                 'lineage as evidence, and circuit breakers — so that compliant behaviour is structurally possible '
                 'rather than inspected after the fact.',
  'epistemic_status': 'instrumental',
  'governance_model': 'algorithmic',
  'id': 'compliance-by-design',
  'label': 'Compliance-by-Design',
  'normative_basis': 'pragmatic',
  'ontological_commitment': 'constructivist',
  'philosophical_lineage': ['technology_philosophy', 'pragmatism'],
  'philosophical_sources': ['Lessig, Lawrence. Code and Other Laws of Cyberspace (1999)',
                            'Kubernetes / Open Policy Agent (OPA) policy-as-code patterns'],
  'pillar': 'cross-pillar',
  'semantic_contract_type': 'coordinating',
  'source_inspiration': 'curated',
  'temporal_ontology': 'state_based',
  'uncertainty_class': 'measurable'},
 {'aliases': ['code is law', 'rules as code', 'legal protection by design'],
  'category': 'regulations',
  'confidence_score': 0.85,
  'cross_pillar_analogs': ['regtech', 'ai-aml-surveillance', 'data-governance'],
  'description': 'The project of translating constitutional values — due process, transparency, contestability, '
                 'accountability, separation of powers — into the architecture of software and data systems. Responds '
                 "to Lessig's claim that 'code is law' by demanding that code itself be subject to constitutional "
                 "constraints, and to Hildebrandt's demand for legal protection by design.",
  'epistemic_status': 'regulatory',
  'governance_model': 'constitutional',
  'id': 'computational-constitutionalism',
  'label': 'Computational Constitutionalism',
  'normative_basis': 'kantian_duty',
  'ontological_commitment': 'constructivist',
  'philosophical_lineage': ['legal_philosophy', 'technology_philosophy', 'republicanism'],
  'philosophical_sources': ['Lessig, Lawrence. Code and Other Laws of Cyberspace (1999)',
                            'Hildebrandt, Mireille. Smart Technologies and the End(s) of Law (2015)',
                            'Zuboff, Shoshana. The Age of Surveillance Capitalism (2019)'],
  'pillar': 'cross-pillar',
  'semantic_contract_type': 'constitutive',
  'source_inspiration': 'curated',
  'temporal_ontology': 'event_based',
  'uncertainty_class': 'ignorance'},
 {'aliases': ['right to contest', 'algorithmic contestability', 'due process in code'],
  'category': 'regulations',
  'confidence_score': 0.85,
  'cross_pillar_analogs': ['ai-aml-surveillance', 'regtech', 'aml-case-management'],
  'description': 'The right and practical ability of a person to challenge a decision that affects them, including '
                 'decisions made or informed by automated systems. Loss of contestability arises when opaque models, '
                 'one-way data flows, and private adjudication remove any meaningful avenue of appeal.',
  'epistemic_status': 'regulatory',
  'governance_model': 'polycentric',
  'id': 'contestability',
  'label': 'Contestability',
  'normative_basis': 'kantian_duty',
  'ontological_commitment': 'realist',
  'philosophical_lineage': ['republicanism', 'legal_philosophy', 'critical_theory'],
  'philosophical_sources': ['Hildebrandt, Mireille. Smart Technologies and the End(s) of Law (2015)',
                            'Zuboff, Shoshana. The Age of Surveillance Capitalism (2019)'],
  'pillar': 'cross-pillar',
  'semantic_contract_type': 'constitutive',
  'source_inspiration': 'curated',
  'temporal_ontology': 'event_based',
  'uncertainty_class': 'ambiguity'},
 {'aliases': ['Wang-Strong 1996',
              'data quality dimensions',
              'DQ framework',
              'beyond accuracy',
              'data-quality-framework'],
  'category': 'best-practices',
  'confidence_score': 1.0,
  'cross_pillar_analogs': ['data-quality'],
  'description': 'Data quality frameworks, pioneered by Wang and Strong (1996), provide a systematic taxonomy of data '
                 'quality dimensions including intrinsic (accuracy, objectivity, believability), contextual '
                 '(relevancy, timeliness, completeness), representational (interpretability, consistency), and '
                 'accessibility (access, security) dimensions.',
  'epistemic_status': 'constitutive',
  'governance_model': 'distributed',
  'id': 'data-quality-framework',
  'label': 'Data Quality Frameworks',
  'normative_basis': 'pragmatic',
  'ontological_commitment': 'realist',
  'philosophical_lineage': ['epistemology_of_measurement', 'error_theory', 'pragmatism'],
  'philosophical_sources': ["Wang, Richard Y., and Diane M. Strong. 'Beyond Accuracy: What Data Quality Means to Data "
                            "Consumers.' JMIS (1996)",
                            "Wand, Yair, and Richard Y. Wang. 'Anchoring Data Quality Dimensions in Ontological "
                            "Foundations.' CACM (1996)"],
  'pillar': 'data-engineering',
  'semantic_contract_type': 'technical',
  'source_inspiration': "Wang, Richard Y., and Diane M. Strong. 'Beyond Accuracy: What Data Quality Means to Data "
                        "Consumers.' Journal of Management Information Systems 12, no. 4 (1996): 5-33.",
  'temporal_ontology': 'state_based',
  'uncertainty_class': 'measurable'},
 {'aliases': ['design'],
  'category': 'specialized',
  'confidence_score': 0.7,
  'cross_pillar_analogs': ['money-laundering-basics', 'acid-transaction-management', 'enterprise-architecture'],
  'description': 'A concept related to design',
  'epistemic_status': 'instrumental',
  'governance_model': 'market_based',
  'id': 'design',
  'label': 'Design',
  'normative_basis': 'utilitarian',
  'ontological_commitment': 'pragmatist',
  'philosophical_lineage': ['behavioral_economics', 'pragmatism'],
  'philosophical_sources': [],
  'pillar': 'stock',
  'semantic_contract_type': 'constitutive',
  'source_inspiration': 'curated',
  'temporal_ontology': 'event_based',
  'uncertainty_class': 'probabilistic'},
 {'aliases': ['platform feudalism', 'data feudalism', 'technofeudalism'],
  'category': 'regulations',
  'confidence_score': 0.85,
  'cross_pillar_analogs': ['data-governance', 'global-sanctions', 'aml-regulatory-framework'],
  'description': 'A speculative-but-dire structural outcome in which private platforms become de facto jurisdictions: '
                 'users cannot meaningfully exit, terms of service function as constitutional law without separation '
                 'of powers, and data plays the role of the land — concentrated in a few hands that govern access, '
                 'opportunity, and even identity.',
  'epistemic_status': 'constitutive',
  'governance_model': 'hierarchical',
  'id': 'digital-neofeudalism',
  'label': 'Digital Neofeudalism',
  'normative_basis': 'rawlsian',
  'ontological_commitment': 'constructivist',
  'philosophical_lineage': ['critical_theory', 'political_philosophy'],
  'philosophical_sources': ['Zuboff, Shoshana. The Age of Surveillance Capitalism (2019)',
                            'Lessig, Lawrence. Code and Other Laws of Cyberspace (1999)'],
  'pillar': 'cross-pillar',
  'semantic_contract_type': 'constitutive',
  'source_inspiration': 'curated',
  'temporal_ontology': 'processual',
  'uncertainty_class': 'ignorance'},
 {'aliases': ['EMH', 'Fama 1970', 'efficient markets', 'random walk hypothesis', 'market efficiency'],
  'category': 'foundations',
  'confidence_score': 1.0,
  'cross_pillar_analogs': ['data-governance'],
  'description': 'The Efficient Market Hypothesis, formalized by Eugene Fama (1970), states that asset prices fully '
                 'reflect all available information. It comes in three forms: weak (past prices), semi-strong (public '
                 'information), and strong (all information, including insider). The EMH provides the benchmark '
                 'against which all market anomalies and behavioral finance findings are measured.',
  'epistemic_status': 'ontological',
  'governance_model': 'market_based',
  'id': 'efficient-market-hypothesis',
  'label': 'Efficient Market Hypothesis (EMH)',
  'normative_basis': 'utilitarian',
  'ontological_commitment': 'fictionalist',
  'philosophical_lineage': ['rational_expectations', 'probability_philosophy', 'liberal_individualism'],
  'philosophical_sources': ["Fama, Eugene F. 'Efficient Capital Markets.' Journal of Finance (1970)",
                            "Fama, Eugene F. 'Market Efficiency, Long-Term Returns, and Behavioral Finance.' JFE "
                            '(1998)',
                            'Malkiel, Burton. A Random Walk Down Wall Street (1973)'],
  'pillar': 'stock',
  'semantic_contract_type': 'constitutive',
  'source_inspiration': "Fama, Eugene F. 'Efficient Capital Markets: A Review of Theory and Empirical Work.' Journal "
                        "of Finance 25, no. 2 (1970): 383-417. Fama, Eugene F. 'Market Efficiency, Long-Term Returns, "
                        "and Behavioral Finance.' Journal of Financial Economics 49, no. 3 (1998): 283-306.",
  'temporal_ontology': 'event_based',
  'uncertainty_class': 'probabilistic'},
 {'aliases': ['enterprisearchitecture'],
  'category': 'specialized',
  'confidence_score': 0.7,
  'cross_pillar_analogs': ['money-laundering-basics', 'design', 'funding'],
  'description': 'A concept related to enterprise-architecture',
  'epistemic_status': 'instrumental',
  'governance_model': 'distributed',
  'id': 'enterprise-architecture',
  'label': 'Enterprise Architecture',
  'normative_basis': 'utilitarian',
  'ontological_commitment': 'realist',
  'philosophical_lineage': ['positivism', 'systems_theory'],
  'philosophical_sources': [],
  'pillar': 'data-engineering',
  'semantic_contract_type': 'technical',
  'source_inspiration': 'curated',
  'temporal_ontology': 'process_based',
  'uncertainty_class': 'measurable'},
 {'aliases': ['Fama-French 3-factor',
              'Fama-French 5-factor',
              'three-factor model',
              'five-factor model',
              'FF3',
              'FF5',
              'fama-french-model'],
  'category': 'advanced-techniques',
  'confidence_score': 1.0,
  'cross_pillar_analogs': ['feature-store', 'network-analysis', 'cyber-aml'],
  'description': 'The Fama-French three-factor model (1993) extends the CAPM by adding size (SMB) and value (HML) '
                 'factors to explain cross-sectional variation in stock returns. The five-factor model (2015) adds '
                 'profitability (RMW) and investment (CMA) factors, capturing the empirical patterns that the original '
                 'CAPM could not explain.',
  'epistemic_status': 'instrumental',
  'governance_model': 'market_based',
  'id': 'fama-french-model',
  'label': 'Fama-French Factor Models',
  'normative_basis': 'pragmatic',
  'ontological_commitment': 'fictionalist',
  'philosophical_lineage': ['probability_philosophy', 'statistical_epistemology', 'empiricism'],
  'philosophical_sources': ["Fama, Eugene F., and Kenneth R. French. 'Common Risk Factors in the Returns on Stocks and "
                            "Bonds.' JFE (1993)",
                            "Fama, Eugene F., and Kenneth R. French. 'A Five-Factor Asset Pricing Model.' JFE (2015)",
                            "Fama, Eugene F., and Kenneth R. French. 'Size, Value, and Momentum in International Stock "
                            "Returns.' JFE (2012)"],
  'pillar': 'stock',
  'semantic_contract_type': 'constitutive',
  'source_inspiration': "Fama, Eugene F., and Kenneth R. French. 'Common Risk Factors in the Returns on Stocks and "
                        "Bonds.' Journal of Financial Economics 33, no. 1 (1993): 3-56. Fama, Eugene F., and Kenneth "
                        "R. French. 'A Five-Factor Asset Pricing Model.' Journal of Financial Economics 116, no. 1 "
                        '(2015): 1-22.',
  'temporal_ontology': 'event_based',
  'uncertainty_class': 'measurable'},
 {'aliases': ['funding'],
  'category': 'specialized',
  'confidence_score': 0.7,
  'cross_pillar_analogs': ['money-laundering-basics', 'acid-transaction-management', 'enterprise-architecture'],
  'description': 'A concept related to funding',
  'epistemic_status': 'instrumental',
  'governance_model': 'market_based',
  'id': 'funding',
  'label': 'Funding',
  'normative_basis': 'utilitarian',
  'ontological_commitment': 'pragmatist',
  'philosophical_lineage': ['behavioral_economics', 'pragmatism'],
  'philosophical_sources': [],
  'pillar': 'stock',
  'semantic_contract_type': 'constitutive',
  'source_inspiration': 'curated',
  'temporal_ontology': 'event_based',
  'uncertainty_class': 'probabilistic'},
 {'aliases': ['Glosten-Milgrom model', 'adverse selection model', 'bid-ask model 1985', 'glosten-milgrom'],
  'category': 'advanced-techniques',
  'confidence_score': 1.0,
  'cross_pillar_analogs': ['data-quality', 'network-analysis', 'cyber-aml'],
  'description': 'The Glosten-Milgrom model explains the bid-ask spread as a consequence of adverse selection: market '
                 'makers widen spreads to protect themselves against informed traders, making the spread a measure of '
                 'information asymmetry in the market.',
  'epistemic_status': 'instrumental',
  'governance_model': 'market_based',
  'id': 'glosten-milgrom',
  'label': 'Glosten-Milgrom (1985) Bid-Ask Model',
  'normative_basis': 'utilitarian',
  'ontological_commitment': 'fictionalist',
  'philosophical_lineage': ['information_asymmetry', 'price_formation_theory', 'game_theory'],
  'philosophical_sources': ["Glosten, Lawrence R., and Paul R. Milgrom. 'Bid, Ask and Transaction Prices.' Journal of "
                            'Financial Economics (1985)',
                            "Akerlof, George. 'The Market for Lemons.' Quarterly Journal of Economics (1970)"],
  'pillar': 'stock',
  'semantic_contract_type': 'constitutive',
  'source_inspiration': "Glosten, Lawrence R., and Paul R. Milgrom. 'Bid, Ask and Transaction Prices in a Specialist "
                        "Market with Heterogeneously Informed Traders.' Journal of Financial Economics 14, no. 1 "
                        '(1985): 71-100.',
  'temporal_ontology': 'state_based',
  'uncertainty_class': 'measurable'},
 {'aliases': ['infrastructure'],
  'category': 'specialized',
  'confidence_score': 0.7,
  'cross_pillar_analogs': ['money-laundering-basics', 'design', 'funding'],
  'description': 'A concept related to infrastructure',
  'epistemic_status': 'instrumental',
  'governance_model': 'distributed',
  'id': 'infrastructure',
  'label': 'Infrastructure',
  'normative_basis': 'utilitarian',
  'ontological_commitment': 'realist',
  'philosophical_lineage': ['positivism', 'systems_theory'],
  'philosophical_sources': [],
  'pillar': 'data-engineering',
  'semantic_contract_type': 'technical',
  'source_inspiration': 'curated',
  'temporal_ontology': 'process_based',
  'uncertainty_class': 'measurable'},
 {'aliases': ['Kyle 1985', 'insider trading model', 'continuous auctions', 'kyle-lambda', 'kyle-model'],
  'category': 'advanced-techniques',
  'confidence_score': 1.0,
  'cross_pillar_analogs': ['transaction-monitoring', 'network-analysis', 'cyber-aml'],
  'description': "Kyle's 1985 model of informed trading and price impact, establishing the theoretical foundation for "
                 'how an informed trader optimally splits orders and how market makers set prices under information '
                 'asymmetry.',
  'epistemic_status': 'instrumental',
  'governance_model': 'market_based',
  'id': 'kyle-model',
  'label': 'Kyle (1985) Insider Trading Model',
  'normative_basis': 'utilitarian',
  'ontological_commitment': 'fictionalist',
  'philosophical_lineage': ['information_asymmetry', 'price_formation_theory', 'rational_expectations'],
  'philosophical_sources': ["Kyle, Albert S. 'Continuous Auctions and Insider Trading.' Econometrica (1985)",
                            'Hayek, Friedrich. The Use of Knowledge in Society (1945)'],
  'pillar': 'stock',
  'semantic_contract_type': 'constitutive',
  'source_inspiration': "Kyle, Albert S. 'Continuous Auctions and Insider Trading.' Econometrica 53, no. 6 (1985): "
                        '1315-35.',
  'temporal_ontology': 'processual',
  'uncertainty_class': 'measurable'},
 {'aliases': ['Armbrust 2021',
              'lakehouse',
              'delta lakehouse',
              'open lakehouse',
              'lakehouse architecture',
              'lakehouse-architecture'],
  'category': 'architecture',
  'confidence_score': 1.0,
  'cross_pillar_analogs': ['aml-data-sharing', 'lakestream-architecture'],
  'description': 'The Lakehouse architecture, formalized by Armbrust et al. (2021), combines the flexibility of data '
                 'lakes (cheap object storage, diverse data types) with the reliability of data warehouses (ACID '
                 'transactions, schema enforcement, performance optimization). It achieves this through a new open '
                 'table format layer (Delta Lake, Iceberg, Hudi) that provides ACID transactions on cloud storage.',
  'epistemic_status': 'constitutive',
  'governance_model': 'distributed',
  'id': 'lakehouse-architecture',
  'label': 'Lakehouse Architecture',
  'normative_basis': 'utilitarian',
  'ontological_commitment': 'constructivist',
  'philosophical_lineage': ['systems_theory', 'data_integration', 'platform_engineering'],
  'philosophical_sources': ["Armbrust, Michael, et al. 'Lakehouse: A New Generation of Open Platforms.' CIDR (2021)",
                            "Armbrust, Michael, et al. 'Delta Lake: High-Performance ACID Table Storage over Cloud "
                            "Object Stores.' VLDB (2020)"],
  'pillar': 'data-engineering',
  'semantic_contract_type': 'technical',
  'source_inspiration': "Armbrust, Michael, et al. 'Lakehouse: A New Generation of Open Platforms that Unify Data "
                        "Warehousing and Advanced Analytics.' Proceedings of CIDR (2021).",
  'temporal_ontology': 'process_based',
  'uncertainty_class': 'measurable'},
 {'aliases': ['lakestream',
              'StreamNative Lakestream',
              'streaming-first lakehouse',
              'streaming-lakehouse',
              'stream batch unification'],
  'category': 'streaming',
  'confidence_score': 1.0,
  'cross_pillar_analogs': ['transaction-monitoring'],
  'description': 'Lakestream Architecture represents the convergence of streaming and lakehouse paradigms, where a '
                 'single copy of data in Kafka topics simultaneously serves real-time stream processing and Iceberg '
                 'table reads. Formalized by StreamNative in 2026, it achieves 95% cost reduction by eliminating '
                 'separate streaming and batch storage layers. The default 2026 stack is Debezium (CDC) → Kafka '
                 '(transport) → Flink (processing) → Iceberg (storage). Extends the lakehouse architecture pioneered '
                 'by Armbrust et al. (2021) with first-class streaming semantics.',
  'epistemic_status': 'constitutive',
  'governance_model': 'distributed',
  'id': 'lakestream-architecture',
  'label': 'Lakestream Architecture',
  'normative_basis': 'utilitarian',
  'ontological_commitment': 'processual',
  'philosophical_lineage': ['event_logging', 'distributed_consensus', 'systems_theory'],
  'philosophical_sources': ["StreamNative. 'Lakestream: One Copy for Streaming and Lakehouse.' (2026)",
                            "Armbrust, Michael, et al. 'Lakehouse: A New Generation of Open Platforms.' CIDR (2021)",
                            "Akidau, Tyler, et al. 'The Dataflow Model.' VLDB (2015)"],
  'pillar': 'data-engineering',
  'semantic_contract_type': 'technical',
  'source_inspiration': 'StreamNative Lakestream architecture whitepaper (2026); Debezium + Kafka + Flink + Iceberg '
                        'stack',
  'temporal_ontology': 'event_based',
  'uncertainty_class': 'measurable'},
 {'aliases': ['three pillars', 'law markets data'],
  'category': 'foundations',
  'confidence_score': 0.85,
  'cross_pillar_analogs': ['aml-regulatory-framework', 'market-microstructure', 'data-governance'],
  'description': 'A cross-pillar framework describing law, markets/money, and data as three layers of one governance '
                 'system running at different speeds: law is the governance protocol (years), markets the incentive '
                 'layer (seconds to quarters), data the information substrate (real-time). Their temporal mismatch '
                 'drives both regulatory lag and enforcement asymmetry.',
  'epistemic_status': 'constitutive',
  'governance_model': 'polycentric',
  'id': 'law-markets-data-triangle',
  'label': 'Law–Markets–Data Triangle',
  'normative_basis': 'contractarian',
  'ontological_commitment': 'processual',
  'philosophical_lineage': ['systems_theory', 'social_epistemology', 'legal_philosophy'],
  'philosophical_sources': ['Hildebrandt, Mireille. Law for Computer Scientists (2020)',
                            'Lessig, Lawrence. Code and Other Laws of Cyberspace (1999)'],
  'pillar': 'cross-pillar',
  'semantic_contract_type': 'coordinating',
  'source_inspiration': 'curated',
  'temporal_ontology': 'processual',
  'uncertainty_class': 'ambiguity'},
 {'aliases': ['Dean-Ghemawat 2004', 'MapReduce', 'map reduce', 'google mapreduce', 'map-reduce'],
  'category': 'foundations',
  'confidence_score': 1.0,
  'cross_pillar_analogs': ['aml-model-validation', 'lob', 'market-microstructure'],
  'description': 'MapReduce, introduced by Dean and Ghemawat (2004), is a programming model for processing large '
                 'datasets in parallel across distributed clusters. It abstracts distributed computation into two '
                 'phases — map (filter/transform) and reduce (aggregate/summarize) — hiding complexities of '
                 'parallelization, fault tolerance, and data distribution from the programmer.',
  'epistemic_status': 'constitutive',
  'governance_model': 'hierarchical',
  'id': 'mapreduce',
  'label': 'MapReduce Programming Model',
  'normative_basis': 'utilitarian',
  'ontological_commitment': 'processual',
  'philosophical_lineage': ['functional_programming', 'distributed_consensus', 'divide_and_conquer'],
  'philosophical_sources': ["Dean, Jeffrey, and Sanjay Ghemawat. 'MapReduce: Simplified Data Processing on Large "
                            "Clusters.' OSDI (2004)",
                            "Dean, Jeffrey, and Sanjay Ghemawat. 'MapReduce: A Flexible Data Processing Tool.' CACM "
                            '(2010)'],
  'pillar': 'data-engineering',
  'semantic_contract_type': 'technical',
  'source_inspiration': "Dean, Jeffrey, and Sanjay Ghemawat. 'MapReduce: Simplified Data Processing on Large "
                        "Clusters.' Proceedings of the 6th Symposium on Operating Systems Design and Implementation "
                        '(OSDI), 2004: 137-50.',
  'temporal_ontology': 'state_based',
  'uncertainty_class': 'measurable'},
 {'aliases': ['Kahneman-Tversky 1979',
              'loss aversion theory',
              'prospect theory',
              'cumulative prospect theory',
              'kahneman-tversky'],
  'category': 'foundations',
  'confidence_score': 1.0,
  'cross_pillar_analogs': ['risk-based-approach', 'data-lake'],
  'description': 'Prospect Theory, developed by Daniel Kahneman and Amos Tversky (1979), describes how people make '
                 'decisions under risk. It shows that individuals evaluate gains and losses relative to a reference '
                 'point, are loss-averse (losses hurt ~2x more than equivalent gains feel good), and overweight small '
                 'probabilities while underweighting large ones.',
  'epistemic_status': 'pragmatic',
  'governance_model': 'market_based',
  'id': 'prospect-theory',
  'label': 'Prospect Theory (Kahneman & Tversky 1979)',
  'normative_basis': 'virtue_ethics',
  'ontological_commitment': 'realist',
  'philosophical_lineage': ['dual_process_theory',
                            'bounded_rationality',
                            'philosophy_of_mind',
                            'experimental_psychology'],
  'philosophical_sources': ["Kahneman, Daniel, and Amos Tversky. 'Prospect Theory.' Econometrica (1979)",
                            'Kahneman, Daniel. Thinking, Fast and Slow (2011)',
                            "Tversky, Amos, and Daniel Kahneman. 'Advances in Prospect Theory.' Journal of Risk and "
                            'Uncertainty (1992)'],
  'pillar': 'stock',
  'semantic_contract_type': 'constitutive',
  'source_inspiration': "Kahneman, Daniel, and Amos Tversky. 'Prospect Theory: An Analysis of Decision under Risk.' "
                        'Econometrica 47, no. 2 (1979): 263-91.',
  'temporal_ontology': 'processual',
  'uncertainty_class': 'probabilistic'},
 {'aliases': ['Fellegi-Sunter', 'entity matching', 'data matching', 'record linkage', 'probabilistic linkage'],
  'category': 'advanced-techniques',
  'confidence_score': 1.0,
  'cross_pillar_analogs': ['entity-resolution', 'high-frequency-trading'],
  'description': 'Record linkage, formalized by Fellegi and Sunter (1969), is the methodology for identifying records '
                 'that refer to the same entity across different data sources. It uses probabilistic matching rules '
                 'based on the agreement patterns of common fields, providing the mathematical foundation for modern '
                 'entity resolution and deduplication.',
  'epistemic_status': 'constitutive',
  'governance_model': 'distributed',
  'id': 'record-linkage',
  'label': 'Record Linkage & Entity Matching',
  'normative_basis': 'pragmatic',
  'ontological_commitment': 'constructivist',
  'philosophical_lineage': ['ontology_matching', 'identity_theory', 'statistical_epistemology'],
  'philosophical_sources': ["Fellegi, Ivan P., and Alan B. Sunter. 'A Theory for Record Linkage.' JASA (1969)",
                            "Winkler, William E. 'Overview of Record Linkage and Current Research Directions.' Census "
                            'Bureau (2006)'],
  'pillar': 'data-engineering',
  'semantic_contract_type': 'technical',
  'source_inspiration': "Fellegi, Ivan P., and Alan B. Sunter. 'A Theory for Record Linkage.' Journal of the American "
                        'Statistical Association 64, no. 328 (1969): 1183-1210.',
  'temporal_ontology': 'state_based',
  'uncertainty_class': 'measurable'},
 {'aliases': ['legal lag', 'pace lag', 'legislative lag'],
  'category': 'regulations',
  'confidence_score': 0.85,
  'cross_pillar_analogs': ['aml-regulatory-framework', 'global-sanctions', 'aml-risk-scoring'],
  'description': 'The temporal gap between the speed of data (real-time), markets (seconds), and law (months to '
                 'years). Because statutes move slowest, rules are always catching up to the behaviour they regulate, '
                 'producing enforcement asymmetry and a window in which novel conduct is unregulated.',
  'epistemic_status': 'regulatory',
  'governance_model': 'hierarchical',
  'id': 'regulatory-lag',
  'label': 'Regulatory Lag',
  'normative_basis': 'utilitarian',
  'ontological_commitment': 'processual',
  'philosophical_lineage': ['legal_philosophy', 'social_epistemology'],
  'philosophical_sources': ['Hart, H. L. A. The Concept of Law (1961)',
                            'Savigny, Friedrich Carl von. On the Vocation of Our Age for Legislation and Jurisprudence '
                            '(1814)'],
  'pillar': 'cross-pillar',
  'semantic_contract_type': 'descriptive',
  'source_inspiration': 'curated',
  'temporal_ontology': 'processual',
  'uncertainty_class': 'ambiguity'},
 {'aliases': ['research'],
  'category': 'specialized',
  'confidence_score': 0.7,
  'cross_pillar_analogs': ['money-laundering-basics', 'acid-transaction-management', 'enterprise-architecture'],
  'description': 'A concept related to research',
  'epistemic_status': 'instrumental',
  'governance_model': 'market_based',
  'id': 'research',
  'label': 'Research',
  'normative_basis': 'utilitarian',
  'ontological_commitment': 'pragmatist',
  'philosophical_lineage': ['behavioral_economics', 'pragmatism'],
  'philosophical_sources': [],
  'pillar': 'stock',
  'semantic_contract_type': 'constitutive',
  'source_inspiration': 'curated',
  'temporal_ontology': 'event_based',
  'uncertainty_class': 'probabilistic'},
 {'aliases': ['Dataflow model',
              'Akidau 2015',
              'Beam model',
              'unbounded processing',
              'stream-processing-model',
              'Apache Beam',
              'stream processing theory'],
  'category': 'advanced-techniques',
  'confidence_score': 1.0,
  'cross_pillar_analogs': ['transaction-monitoring', 'lakestream-architecture', 'entity-resolution'],
  'description': 'The Dataflow Model, introduced by Akidau et al. (2015), provides a unified framework for processing '
                 'both batch and streaming data. It defines a general approach to handling unbounded, out-of-order '
                 'data by separating the what (computation via operators), where (windowing), when (triggering), and '
                 'how (accumulation) of stream processing.',
  'epistemic_status': 'constitutive',
  'governance_model': 'distributed',
  'id': 'stream-processing-model',
  'label': 'Stream Processing & The Dataflow Model',
  'normative_basis': 'utilitarian',
  'ontological_commitment': 'processual',
  'philosophical_lineage': ['event_logging', 'distributed_consensus', 'temporal_logic'],
  'philosophical_sources': ["Akidau, Tyler, et al. 'The Dataflow Model.' VLDB (2015)",
                            "Akidau, Tyler, et al. 'MillWheel: Fault-Tolerant Stream Processing at Internet Scale.' "
                            'VLDB (2013)'],
  'pillar': 'data-engineering',
  'semantic_contract_type': 'technical',
  'source_inspiration': "Akidau, Tyler, et al. 'The Dataflow Model: A Practical Approach to Balancing Correctness, "
                        "Latency, and Cost in Massive-Scale, Unbounded, Out-of-Order Data Processing.' Proceedings of "
                        'the VLDB Endowment 8, no. 12 (2015): 1792-1803.',
  'temporal_ontology': 'event_based',
  'uncertainty_class': 'measurable'},
 {'aliases': ['Takáts 2007',
              'crying wolf theory',
              'STR effectiveness',
              'aml alerting theory',
              'transaction-monitoring-theory'],
  'category': 'transaction-monitoring',
  'confidence_score': 1.0,
  'cross_pillar_analogs': ['data-quality'],
  'description': "Transaction monitoring theory, including Takáts (2007) 'A Theory of Crying Wolf,' analyzes the "
                 'economics and effectiveness of suspicious transaction reporting. It models the trade-off between '
                 'catching true positives (actual money laundering) and generating false positives, showing how poorly '
                 'calibrated thresholds and risk aversion among compliance officers can flood the system with '
                 'low-value reports.',
  'epistemic_status': 'pragmatic',
  'governance_model': 'hierarchical',
  'id': 'transaction-monitoring-theory',
  'label': 'Transaction Monitoring Theory',
  'normative_basis': 'utilitarian',
  'ontological_commitment': 'critical_realist',
  'philosophical_lineage': ['game_theory', 'principal_agent', 'skepticism', 'surveillance_studies'],
  'philosophical_sources': ["Takáts, Elöd. 'A Theory of Crying Wolf.' JLEO (2011)"],
  'pillar': 'aml',
  'semantic_contract_type': 'evaluative',
  'source_inspiration': "Takáts, Elöd. 'A Theory of 'Crying Wolf': The Economics of Money Laundering Enforcement.' "
                        'Journal of Law, Economics, and Organization 27, no. 1 (2011): 187-215. (IMF Working Paper '
                        '2007)',
  'temporal_ontology': 'processual',
  'uncertainty_class': 'knightian'},
 {'aliases': ['uxdesignpatterns'],
  'category': 'specialized',
  'confidence_score': 0.7,
  'cross_pillar_analogs': ['money-laundering-basics', 'design', 'funding'],
  'description': 'A concept related to ux-design-patterns',
  'epistemic_status': 'instrumental',
  'governance_model': 'distributed',
  'id': 'ux-design-patterns',
  'label': 'Ux Design Patterns',
  'normative_basis': 'utilitarian',
  'ontological_commitment': 'realist',
  'philosophical_lineage': ['positivism', 'systems_theory'],
  'philosophical_sources': [],
  'pillar': 'data-engineering',
  'semantic_contract_type': 'technical',
  'source_inspiration': 'curated',
  'temporal_ontology': 'process_based',
  'uncertainty_class': 'measurable'}]

PILLAR_EXTRA_RELATION_SEEDS: list[tuple] = [('adverse-media', 'kyc', 'requires', 'aml'),
 ('ai-act-high-risk', 'ai-conformity-assessment', 'requires', 'data-engineering'),
 ('ai-aml-surveillance', 'ml-pipeline', 'requires', 'aml'),
 ('ai-aml-surveillance', 'transaction-monitoring', 'requires', 'aml'),
 ('ai-conformity-assessment', 'ml-pipeline', 'requires', 'data-engineering'),
 ('ai-hardware', 'semiconductor-industry', 'requires', 'stock'),
 ('algorithmic-cascade', 'algorithmic-trading', 'influences', 'cross-pillar'),
 ('algorithmic-cascade', 'aml-risk-scoring', 'related_to', 'cross-pillar'),
 ('algorithmic-trading', 'execution-algos', 'requires', 'stock'),
 ('alternative-data', 'technical-analysis', 'requires', 'stock'),
 ('aml-case-management', 'sar', 'requires', 'aml'),
 ('aml-compliance-basics', 'aml-regulatory-framework', 'requires', 'aml'),
 ('aml-compliance-basics', 'money-laundering-basics', 'requires', 'aml'),
 ('aml-continuous-monitoring', 'transaction-monitoring', 'requires', 'aml'),
 ('aml-data-governance', 'aml-program', 'requires', 'aml'),
 ('aml-data-sharing', 'aml-data-governance', 'requires', 'aml'),
 ('aml-effectiveness', 'aml-regulatory-framework', 'related_to', 'aml'),
 ('aml-esg-risk', 'aml-compliance-basics', 'requires', 'aml'),
 ('aml-international', 'sar', 'requires', 'aml'),
 ('aml-model-validation', 'aml-oracle', 'requires', 'aml'),
 ('aml-optimization', 'regtech', 'requires', 'aml'),
 ('aml-oracle', 'regtech', 'requires', 'aml'),
 ('aml-program', 'aml-compliance-basics', 'requires', 'aml'),
 ('aml-program-reform', 'aml-program', 'influences', 'aml'),
 ('aml-program-reform', 'aml-regulatory-framework', 'part_of', 'aml'),
 ('aml-program-reform', 'beneficial-ownership', 'related_to', 'aml'),
 ('aml-program-reform', 'bsa', 'regulates', 'aml'),
 ('aml-program-reform', 'risk-based-approach', 'influences', 'aml'),
 ('aml-reporting-dashboard', 'regulatory-reporting', 'requires', 'aml'),
 ('aml-risk-scoring', 'cdd', 'requires', 'aml'),
 ('aml-risk-scoring', 'risk-based-approach', 'requires', 'aml'),
 ('aml-threat-intel', 'transaction-monitoring', 'requires', 'aml'),
 ('aml-training', 'aml-compliance-basics', 'requires', 'aml'),
 ('apache-flink', 'real-time-analytics', 'requires', 'data-engineering'),
 ('apache-iceberg', 'lakehouse', 'requires', 'data-engineering'),
 ('apache-kafka', 'streaming', 'requires', 'data-engineering'),
 ('arrow-parquet', 'lakehouse', 'requires', 'data-engineering'),
 ('batch-processing', 'data-pipeline', 'requires', 'data-engineering'),
 ('behavioral-finance', 'portfolio-optimization', 'requires', 'stock'),
 ('black-scholes', 'asset-pricing', 'part_of', 'stock'),
 ('black-scholes', 'options-trading', 'enables', 'stock'),
 ('bsa', 'aml-regulatory-framework', 'requires', 'aml'),
 ('capital-asset-pricing-model', 'asset-pricing', 'part_of', 'stock'),
 ('capital-asset-pricing-model', 'portfolio-optimization', 'enables', 'stock'),
 ('carry-trade', 'quantitative-trading', 'requires', 'stock'),
 ('cdc', 'apache-kafka', 'requires', 'data-engineering'),
 ('cdd', 'kyc', 'requires', 'aml'),
 ('change-data-capture', 'cdc', 'requires', 'data-engineering'),
 ('commodity-trading', 'market-participants', 'requires', 'stock'),
 ('compliance-by-design', 'aml-continuous-monitoring', 'enables', 'cross-pillar'),
 ('compliance-by-design', 'aml-regulatory-framework', 'implements', 'cross-pillar'),
 ('compliance-by-design', 'computational-constitutionalism', 'part_of', 'cross-pillar'),
 ('compliance-by-design', 'data-governance', 'requires', 'cross-pillar'),
 ('computational-constitutionalism', 'regtech', 'influences', 'cross-pillar'),
 ('contestability', 'ai-aml-surveillance', 'regulates', 'cross-pillar'),
 ('contestability', 'regtech', 'influences', 'cross-pillar'),
 ('correspondent-banking', 'trade-finance-aml', 'requires', 'aml'),
 ('cross-asset-trading', 'portfolio-optimization', 'requires', 'stock'),
 ('crypto-aml', 'transaction-monitoring', 'requires', 'aml'),
 ('crypto-markets', 'market-participants', 'requires', 'stock'),
 ('crypto-travel-rule', 'travel-rule', 'requires', 'aml'),
 ('ctr', 'transaction-monitoring', 'requires', 'aml'),
 ('cyber-aml', 'fraud-detection', 'requires', 'aml'),
 ('dagster', 'dataops', 'requires', 'data-engineering'),
 ('dark-pools', 'trading-venues', 'requires', 'stock'),
 ('data-act-interoperability', 'data-mesh', 'requires', 'data-engineering'),
 ('data-catalog', 'data-mesh', 'requires', 'data-engineering'),
 ('data-contract-testing', 'data-contracts', 'requires', 'data-engineering'),
 ('data-contracts', 'data-governance', 'requires', 'data-engineering'),
 ('data-cost-intelligence', 'pipeline-cost-optimization', 'requires', 'data-engineering'),
 ('data-discovery', 'data-catalog', 'requires', 'data-engineering'),
 ('data-governance', 'data-quality', 'requires', 'data-engineering'),
 ('data-lake', 'data-warehouse', 'requires', 'data-engineering'),
 ('data-lineage', 'data-observability', 'requires', 'data-engineering'),
 ('data-mesh', 'lakehouse', 'requires', 'data-engineering'),
 ('data-mesh-governance', 'data-mesh', 'requires', 'data-engineering'),
 ('data-observability', 'data-pipeline', 'requires', 'data-engineering'),
 ('data-platform-kpis', 'data-warehouse', 'requires', 'data-engineering'),
 ('data-quality', 'data-pipeline', 'requires', 'data-engineering'),
 ('data-quality-framework', 'data-quality', 'part_of', 'data-engineering'),
 ('data-quality-monitoring', 'data-quality', 'requires', 'data-engineering'),
 ('data-quality-sla', 'data-quality-monitoring', 'requires', 'data-engineering'),
 ('data-security', 'data-governance', 'requires', 'data-engineering'),
 ('data-versioning', 'data-lake', 'requires', 'data-engineering'),
 ('data-warehouse', 'data-pipeline', 'requires', 'data-engineering'),
 ('data-warehouse-design', 'data-warehouse', 'requires', 'data-engineering'),
 ('dataops', 'data-pipeline', 'requires', 'data-engineering'),
 ('dbt', 'dataops', 'requires', 'data-engineering'),
 ('debiasing-pipeline', 'data-quality', 'requires', 'data-engineering'),
 ('differential-privacy', 'data-security', 'requires', 'data-engineering'),
 ('digital-neofeudalism', 'contestability', 'related_to', 'cross-pillar'),
 ('digital-neofeudalism', 'data-governance', 'influences', 'cross-pillar'),
 ('distributed-systems', 'data-pipeline', 'requires', 'data-engineering'),
 ('dora-ict-risk', 'data-governance', 'requires', 'data-engineering'),
 ('earnings-analysis', 'equity-basics', 'requires', 'stock'),
 ('edd', 'cdd', 'requires', 'aml'),
 ('efficient-market-hypothesis', 'asset-pricing', 'part_of', 'stock'),
 ('elt', 'data-pipeline', 'requires', 'data-engineering'),
 ('elt-pipeline', 'elt', 'requires', 'data-engineering'),
 ('entity-resolution', 'kyc', 'requires', 'aml'),
 ('equity-basics', 'market-participants', 'requires', 'stock'),
 ('esg-double-materiality', 'esg-investing', 'requires', 'stock'),
 ('esg-investing', 'portfolio-optimization', 'requires', 'stock'),
 ('etf-creation', 'market-participants', 'requires', 'stock'),
 ('etf-trading', 'etf-creation', 'requires', 'stock'),
 ('etl', 'elt', 'requires', 'data-engineering'),
 ('event-driven-trading', 'quantitative-trading', 'requires', 'stock'),
 ('execution-algos', 'order-types', 'requires', 'stock'),
 ('factor-investing', 'portfolio-optimization', 'requires', 'stock'),
 ('fairness-metrics', 'debiasing-pipeline', 'requires', 'data-engineering'),
 ('fama-french-model', 'asset-pricing', 'enables', 'stock'),
 ('fama-french-model', 'factor-investing', 'part_of', 'stock'),
 ('fatf-recommendations', 'aml-regulatory-framework', 'part_of', 'aml'),
 ('fatf-recommendations', 'aml-regulatory-framework', 'requires', 'aml'),
 ('federated-learning', 'differential-privacy', 'requires', 'data-engineering'),
 ('fincen-boi', 'beneficial-ownership', 'requires', 'aml'),
 ('fincrime-intelligence', 'aml-threat-intel', 'requires', 'aml'),
 ('fixed-income', 'market-participants', 'requires', 'stock'),
 ('fraud-detection', 'transaction-monitoring', 'requires', 'aml'),
 ('gdpr-anonymization', 'data-governance', 'requires', 'data-engineering'),
 ('gdpr-synthetic-data', 'gdpr-anonymization', 'requires', 'data-engineering'),
 ('global-sanctions', 'sanctions-screening', 'requires', 'aml'),
 ('glosten-milgrom', 'market-making', 'enables', 'stock'),
 ('glosten-milgrom', 'market-microstructure', 'part_of', 'stock'),
 ('hawkes-process', 'high-frequency-trading', 'requires', 'stock'),
 ('hedge-funds', 'portfolio-optimization', 'requires', 'stock'),
 ('high-frequency-trading', 'market-microstructure', 'requires', 'stock'),
 ('kyc', 'aml-compliance-basics', 'requires', 'aml'),
 ('kyle-model', 'market-impact', 'enables', 'stock'),
 ('kyle-model', 'market-microstructure', 'part_of', 'stock'),
 ('kyle-model', 'transaction-monitoring', 'related_to', 'cross-pillar'),
 ('lakehouse', 'data-lake', 'requires', 'data-engineering'),
 ('lakehouse-architecture', 'aml-data-governance', 'related_to', 'cross-pillar'),
 ('lakehouse-architecture', 'apache-iceberg', 'enables', 'data-engineering'),
 ('lakehouse-architecture', 'lakehouse', 'part_of', 'data-engineering'),
 ('lakestream-architecture', 'apache-flink', 'requires', 'data-engineering'),
 ('lakestream-architecture', 'apache-iceberg', 'requires', 'data-engineering'),
 ('lakestream-architecture', 'apache-kafka', 'requires', 'data-engineering'),
 ('lakestream-architecture', 'lakehouse-architecture', 'supersedes', 'data-engineering'),
 ('lakestream-architecture', 'stream-processing-model', 'enables', 'data-engineering'),
 ('law-markets-data-triangle', 'aml-regulatory-framework', 'influences', 'cross-pillar'),
 ('law-markets-data-triangle', 'data-governance', 'requires', 'cross-pillar'),
 ('law-markets-data-triangle', 'market-microstructure', 'influences', 'cross-pillar'),
 ('lob', 'order-book', 'requires', 'stock'),
 ('machine-learning-markets', 'ml-pipeline', 'requires', 'stock'),
 ('machine-learning-markets', 'quantitative-trading', 'requires', 'stock'),
 ('macro-analysis', 'market-indices', 'requires', 'stock'),
 ('mapreduce', 'data-pipeline', 'enables', 'data-engineering'),
 ('market-data', 'data-pipeline', 'requires', 'stock'),
 ('market-data', 'trading-venues', 'requires', 'stock'),
 ('market-impact', 'market-microstructure', 'requires', 'stock'),
 ('market-indices', 'equity-basics', 'requires', 'stock'),
 ('market-making', 'execution-algos', 'requires', 'stock'),
 ('market-surveillance', 'data-pipeline', 'requires', 'stock'),
 ('market-surveillance', 'market-microstructure', 'requires', 'stock'),
 ('mean-reversion', 'statistical-arbitrage', 'requires', 'stock'),
 ('metric-store', 'data-warehouse', 'requires', 'data-engineering'),
 ('mica-crypto-assets', 'crypto-aml', 'requires', 'aml'),
 ('ml-pipeline', 'data-pipeline', 'requires', 'data-engineering'),
 ('momentum-trading', 'quantitative-trading', 'requires', 'stock'),
 ('money-laundering-basics', 'financial-crime-types', 'requires', 'aml'),
 ('network-analysis', 'fincrime-intelligence', 'requires', 'aml'),
 ('nis2-cyber-resilience', 'dora-ict-risk', 'requires', 'data-engineering'),
 ('options-trading', 'volatility-trading', 'requires', 'stock'),
 ('orchestration', 'data-pipeline', 'requires', 'data-engineering'),
 ('order-book', 'order-types', 'requires', 'stock'),
 ('order-types', 'equity-basics', 'requires', 'stock'),
 ('payment-fraud', 'fraud-detection', 'requires', 'aml'),
 ('pep', 'cdd', 'requires', 'aml'),
 ('pipeline-cost-optimization', 'data-platform-kpis', 'requires', 'data-engineering'),
 ('portfolio-optimization', 'equity-basics', 'requires', 'stock'),
 ('prospect-theory', 'behavioral-finance', 'part_of', 'stock'),
 ('quantitative-trading', 'algorithmic-trading', 'requires', 'stock'),
 ('query-optimization', 'data-warehouse-design', 'requires', 'data-engineering'),
 ('real-time-analytics', 'streaming', 'requires', 'data-engineering'),
 ('real-time-analytics-architecture', 'real-time-analytics', 'requires', 'data-engineering'),
 ('record-linkage', 'data-quality', 'enables', 'data-engineering'),
 ('record-linkage', 'entity-resolution', 'enables', 'data-engineering'),
 ('regime-detection', 'machine-learning-markets', 'requires', 'stock'),
 ('regtech', 'data-pipeline', 'requires', 'aml'),
 ('regtech', 'transaction-monitoring', 'requires', 'aml'),
 ('regulatory-filing', 'regulatory-reporting', 'requires', 'aml'),
 ('regulatory-lag', 'aml-regulatory-framework', 'influences', 'cross-pillar'),
 ('regulatory-reporting', 'transaction-monitoring', 'requires', 'aml'),
 ('reverse-etl', 'data-warehouse', 'requires', 'data-engineering'),
 ('risk-based-approach', 'aml-compliance-basics', 'requires', 'aml'),
 ('risk-parity', 'portfolio-optimization', 'requires', 'stock'),
 ('sanctions-screening', 'kyc', 'requires', 'aml'),
 ('sar', 'transaction-monitoring', 'requires', 'aml'),
 ('schema-migration', 'data-versioning', 'requires', 'data-engineering'),
 ('schema-registry', 'schema-migration', 'requires', 'data-engineering'),
 ('semiconductor-industry', 'supply-chain-analysis', 'requires', 'stock'),
 ('statistical-arbitrage', 'quantitative-trading', 'requires', 'stock'),
 ('stock-lending', 'market-participants', 'requires', 'stock'),
 ('str', 'transaction-monitoring', 'requires', 'aml'),
 ('stream-processing-model', 'streaming', 'part_of', 'data-engineering'),
 ('streaming', 'data-pipeline', 'requires', 'data-engineering'),
 ('supply-chain-analysis', 'macro-analysis', 'requires', 'stock'),
 ('tbml', 'trade-finance-aml', 'requires', 'aml'),
 ('technical-analysis', 'market-data', 'requires', 'stock'),
 ('trade-finance-aml', 'transaction-monitoring', 'requires', 'aml'),
 ('trading-venues', 'distributed-systems', 'requires', 'stock'),
 ('trading-venues', 'order-types', 'requires', 'stock'),
 ('transaction-monitoring', 'kyc', 'requires', 'aml'),
 ('transaction-monitoring', 'risk-based-approach', 'requires', 'aml'),
 ('transaction-monitoring-theory', 'transaction-monitoring', 'part_of', 'aml'),
 ('travel-rule', 'crypto-aml', 'requires', 'aml'),
 ('volatility-arbitrage', 'volatility-trading', 'requires', 'stock'),
 ('volatility-surface', 'volatility-trading', 'requires', 'stock'),
 ('volatility-trading', 'quantitative-trading', 'requires', 'stock'),
 ('vpin', 'market-impact', 'requires', 'stock')]
