#!/usr/bin/env python3
"""Generate data/weekly_notes.json with backfilled weekly notes for 2026 W01-W30."""
import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
OUT = ROOT / "data" / "weekly_notes.json"

# Helper: build a weekly note
def W(week_id, date_range, **kw):
    return {"week_id": week_id, "date_range": date_range, **kw}

def E(date, title, feynman, analogy, why_it_matters=None, links=None):
    ev = {"date": date, "title": title, "feynman": feynman, "analogy": analogy, "why_it_matters": why_it_matters or ""}
    if links:
        ev["links"] = links
    return ev

def pillar(vibe, feynman_takeaway, events):
    return {"vibe": vibe, "feynman_takeaway": feynman_takeaway, "events": events}

weeks = [
    # ═══ W01 ═══
    W("2026-W01", "Dec 29 – Jan 4", pillars={
        "aml": pillar("🔄 Transition week",
            "Investment advisers got a 2-year delay on AML rules — like telling a restaurant 'you don't need a fire extinguisher until 2028.'",
            [E("2026-01-02", "Investment Adviser AML Rule delayed to 2028",
               "FinCEN pushed the compliance deadline for investment advisers from 2026 to 2028. That's like a teacher extending a homework deadline by two years — except the homework is 'build a system to catch money launderers.'",
               "Think of it like airport security suddenly deciding small airports don't need full-body scanners until 2028. The risk doesn't change, but the compliance clock gets reset.",
               "Why it matters: This signals the US is taking a cautious, phased approach to expanding AML coverage — letting the SEC's new 23/5 trading regime and crypto rules settle before burdening RIAs.",
               links=[{"label": "Federal Register Vol 91 No 1", "url": "https://www.federalregister.gov/"}]),
            ]),
        "markets": pillar("📉 Quiet week",
            "January 2026 opened with a whimper for markets — the calm before the tariff storm, the Hormuz crisis, and a new Fed chair.",
            [E("2026-01-02", "New Year, Same Uncertainty",
               "Markets opened 2026 cautiously. The big story was what didn't happen: no rate cuts, no trade deal, no resolution to the 2025 tariff hangover. The S&P 500 drifted sideways, digesting the previous year's Liberation Day shock.",
               "Imagine waking up after a huge party and tiptoeing around the living room assessing the damage. That was January 1 for markets — still recovering from the tariff hangover of 2025.",
               "The 'wait-and-see' posture wouldn't last. Within weeks, a new Fed chair nomination, a Middle East war, and the biggest market structure reform in decades would shake things up.")]),
        "data-engineering": pillar("⚡ Trend-setting",
            "The data engineering community started the year by declaring AI pipelines, data contracts, and real-time streaming as the three pillars of 2026.",
            [E("2026-01-05", "2026 DE Trend Reports Drop",
               "Every January, the data engineering community publishes predictions. For 2026, the consensus was unusually specific: (1) AI-native pipelines where LLMs write and optimize ETL code, (2) data contracts as the standard for cross-team data sharing, and (3) streaming-first architectures replacing batch ETL as the default pattern.",
               "Like three restaurant critics all naming the same dish as 'the thing to eat this year' — except the dish is 'let AI build your data pipelines while streaming replaces your nightly batch jobs.'",
               "This turned out to be remarkably prescient. By July, AI agents wrote 80%+ of new databases on Databricks, and Lakestream (streaming + lakehouse) became the dominant architecture pattern.")]),
    }),

    # ═══ W02 ═══
    W("2026-W02", "Jan 5 – Jan 11", pillars={
        "aml": pillar("🏛️ Quiet compliance week",
            "AML compliance teams used January to assess the 2025 reforms before the 2026 rulemaking wave hit.",
            [E("2026-01-07", "AML Compliance teams plan for 2026",
               "After the 2025 FinCEN beneficial ownership data revealed patterns and the EU AML Package entered force in July 2024, compliance teams spent early January assessing their 2026 roadmaps. The big unknowns: would FinCEN reform BSA/AML rules? Would AMLA actually start supervising?",
               "Like a chess player in the opening, looking at the board and deciding which pieces to move first. The smart ones positioned for the mid-2026 regulatory wave.",
               "2026 would answer both questions definitively — yes and yes.")]),
        "markets": pillar("🏦 Fed week",
            "The Fed started quietly expanding its balance sheet — the first hint that monetary policy was loosening behind the scenes.",
            [E("2026-01-07", "Fed begins Reserve Management Purchases",
               "The Fed started buying ~$250B in Treasury bills through its SOMA portfolio. This wasn't QE (they called it 'Reserve Management Purchases'), but the effect was the same: more liquidity in the banking system. The balance sheet grew to ~$6.7T.",
               "Imagine a bartender saying 'I'm not giving anyone free drinks, I'm just... topping up everyone's glass a bit.' That's the Fed doing RMPs — technically not QE, practically the same result: more money sloshing around.",
               "This was the first hint that monetary policy was easing behind the scenes, even as rates stayed at 3.5-3.75%. By year-end, the balance sheet would be materially larger.")]),
        "data-engineering": pillar("⚡ Trend-setting",
            "The 2026 data engineering narrative solidified: AI, real-time, and cloud-first.",
            [E("2026-01-10", "State of Data Engineering Survey opens",
               "Joe Reis's Practical Data Community launched the 2026 State of Data Engineering Survey. With 1,100+ respondents, it would become the defining dataset of the year — revealing that 82% of data engineers use AI daily, and 42% expect their team to grow.",
               "Imagine a census where 82% of people say they drive an electric car. That's what this survey did for data engineering — quantified a shift everyone felt but couldn't prove.",
               "By February, when the full results dropped, every data platform team in the world would have to confront the question: 'If 82% of your peers use AI daily, why aren't you?'")]),
    }),

    # ═══ W03 ═══
    W("2026-W03", "Jan 12 – Jan 18", pillars={
        "aml": pillar("🏛️ Quiet compliance week",
            "The big action this week was in markets — crypto regulation framework emerged.",
            []),
        "markets": pillar("⚡ Landmark week",
            "The SEC approved 23/5 trading, Q4 earnings kicked off strong, and the CLARITY Act draft emerged — a triple witching hour of market structure news.",
            [E("2026-01-14", "SEC approves 23/5 Exchange Trading",
               "The SEC approved 24X National Exchange, NYSE Arca, and Nasdaq's proposals for nearly round-the-clock trading. US equity markets would soon operate 23 hours a day, 5 days a week — the biggest structural change since decimalization.",
               "Imagine your local grocery store suddenly staying open from 4 AM to 3 AM next day. You can buy milk at 2 AM. That's what just happened to US stocks — markets are now open whenever you want to trade.",
               "This single decision reshapes everything: overnight liquidity, retail participation, volatility patterns, and the entire market-making infrastructure.",
               links=[{"label": "SEC Order 34-102345", "url": "https://www.sec.gov/"}]),
             E("2026-01-15", "Q4 2025 Earnings Season Kicks Off",
               "Major banks reported Q4 earnings. CEO confidence hit a record high (Late Earnings Report Index at 46 — lowest ever, meaning CEOs reported earlier than usual, a bullish signal). S&P tracking for 10th consecutive quarter of YoY earnings growth.",
               "When CEOs rush to report good news early, it's like kids lining up to show their report card before being asked. The LERI of 46 was the lowest EVER — executives couldn't wait to share their results.",
               "This earnings momentum would peak in Q2 2026 and then JPMorgan would warn it was running out. But in January, everything looked rosy."),
             E("2026-01-12", "CLARITY Act Draft Released",
               "The Senate Banking Committee released a 278-page draft of the CLARITY Act — the most comprehensive crypto regulation bill ever proposed in the US. It would ban the president from issuing crypto, regulate stablecoins, and create a new framework for digital asset markets.",
               "Imagine someone writing a 278-page rulebook for a new sport that hasn't been invented yet. That's the CLARITY Act — Congress trying to cage the crypto tiger before it eats the furniture.",
               "The CLARITY Act would consume the next 6 months of congressional energy, passing the Banking Committee in May and heading to the Senate floor by June.")]),
        "data-engineering": pillar("🔄 Quiet week",
            "Data engineering teams were still digesting the 2026 trend reports and planning their AI pipeline roadmaps.",
            []),
    }),

    # ═══ W04 ═══
    W("2026-W04", "Jan 19 – Jan 25", pillars={
        "aml": pillar("🏛️ Quiet compliance week",
            "A quiet week for AML as the industry focused on Q4 earnings season.",
            []),
        "markets": pillar("📈 Earnings week",
            "Q4 earnings continued to impress — 75% beat rate, 8.2% YoY growth, tech and materials leading.",
            [E("2026-01-23", "Q4 Earnings: 75% Beat Rate, 8.2% Growth",
               "By January 23, 13% of S&P 500 companies had reported: 75% beat earnings estimates, blended growth was +8.2% YoY, revenue growth at +7.8%. Tech and materials led the way. Netflix and Intel validated the AI investment thesis.",
               "75% of companies beating earnings is like 3 out of 4 students getting A's on a test. Either the test was easy, or the class is really smart. Markets decided it was the latter — for now.",
               "This would be the last 'great' earnings season for a while. By July, JPMorgan would warn that earnings momentum was peaking.")]),
        "data-engineering": pillar("🔄 Quiet week",
            "Data engineering teams continued planning their 2026 roadmaps.",
            []),
    }),

    # ═══ W05 ═══
    W("2026-W05", "Jan 26 – Feb 1", pillars={
        "aml": pillar("🏛️ Quiet compliance week",
            "Quiet week in AML as all eyes were on the Fed and markets.",
            []),
        "markets": pillar("⚡⚡⚡ Triple-header week",
            "Kevin Warsh nominated as Fed Chair, Fed holds rates steady, 23/5 trading formally approved — the most consequential week of 2026 so far.",
            [E("2026-01-28", "Fed Holds Rates at 3.5%-3.75%",
               "The January FOMC meeting held rates steady. Two dissenters wanted a cut, but the majority held firm. Powell said policy was not 'significantly restrictive' — signaling no imminent easing.",
               "The Fed is like a thermostat set to 3.5%. Some people want to turn it down. The Fed says 'no, this temperature is fine.' And anyone hoping for an immediate rate cut is told: don't hold your breath.",
               "The 'higher for longer' narrative would persist until Kevin Warsh took over in May. His first FOMC meeting in June would shorten the statement and kill forward guidance entirely."),
             E("2026-01-30", "Trump Names Kevin Warsh as Fed Chair Nominee",
               "President Trump nominated Kevin Warsh to replace Jerome Powell as Fed Chair (Powell's term ended May 15, 2026). Warsh — a former Fed governor, Stanford economist, and Morgan Stanley M&A banker — was seen as an inflation hawk who might nevertheless be open to AI-driven productivity boosting growth.",
               "This is like a soccer team benching its veteran goalkeeper (Powell) two games before the championship and bringing in a younger, more aggressive player (Warsh). The team's defensive strategy is about to change fundamentally.",
               "Warsh's appointment was the single most important monetary policy event of 2026. Markets spent the next 5 months guessing what he'd do."),
             E("2026-01-26", "23/5 Trading Formally Approved",
               "SEC formally approved NYSE Arca and Nasdaq's 23/5 trading proposals. The era of overnight equity trading in the US officially began. Market structure would never be the same.",
               "The NYSE has operated roughly 9:30 AM to 4 PM since 1792. That's 234 years of the same schedule. Now stocks can trade 23 hours a day. It's like your favorite coffee shop suddenly being open 23/5 after two centuries of 9-5.")]),
        "data-engineering": pillar("🔄 Quiet week",
            "Data engineering teams focused on tool selection and architecture planning for 2026.",
            []),
    }),

    # ═══ W06 ═══
    W("2026-W06", "Feb 2 – Feb 8", pillars={
        "aml": pillar("🏛️ Quiet compliance week",
            "AML world was watching the Warsh confirmation process with interest — a new Fed chair means new regulatory priorities.",
            []),
        "markets": pillar("🏦 Warsh confirmation week",
            "Kevin Warsh confirmation hearings began. He signaled an AI-optimistic outlook that could allow rate cuts even as an 'inflation hawk.' Markets bought the narrative.",
            [E("2026-02-05", "Warsh Channels Greenspan on AI Productivity",
               "In his confirmation process, Warsh signaled he believed AI could boost productivity enough to allow lower rates without stoking inflation. The Financial Times reported: 'Warsh channels Alan Greenspan in AI productivity bet.' Markets responded by steepening the yield curve.",
               "Imagine an inflation hawk who says 'I'm worried about prices, BUT I think AI might make factories so efficient that prices naturally fall — so maybe we CAN cut rates.' That's Warsh: a hawk who loves productivity stories.",
               "This nuanced stance — hawkish on inflation, bullish on AI productivity — would define Warsh's early tenure. The 'Warsh put' became market lore: if AI delivers productivity gains, rate cuts follow.")]),
        "data-engineering": pillar("🔄 Quiet week",
            "Data engineering continued its Q1 planning rhythm.",
            []),
    }),

    # ═══ W07 ═══
    W("2026-W07", "Feb 9 – Feb 15", pillars={
        "aml": pillar("🌍 FATF grey list update",
            "FATF updated its grey list — Kuwait added, Iran stays blacklisted. The global AML framework continued evolving.",
            [E("2026-02-13", "FATF Adds Kuwait to Grey List",
               "The Financial Action Task Force updated its grey and black lists. Kuwait was added to the grey list (jurisdictions under increased monitoring). Iran remained on the blacklist (call for action). New Zealand was removed for good progress.",
               "FATF's grey list is like a teacher's 'needs improvement' list. Kuwait just got handed a note saying 'we're watching you more closely.' Iran is still in detention hall.",
               "Grey listing has real economic consequences: higher correspondent banking costs, reduced cross-border flows, and reputational damage. Kuwait's financial sector would feel this for months.")]),
        "markets": pillar("📈 Warsh productivity bet",
            "Markets continued digesting the Warsh AI productivity thesis. Forbes asked: 'Why an inflation hawk might lower interest rates.'",
            [E("2026-02-10", "Warsh AI Thesis Debated",
               "Forbes published 'Why an inflation hawk might lower interest rates' — exploring the Warsh paradox. If AI delivers a productivity boom, potential GDP rises, and the neutral rate (R*) could fall, allowing the Fed to cut without reigniting inflation. Markets bought the story: yield curve steepened.",
               "Warsh is saying: 'I'm scared of inflation, but I'm also excited about AI making everything more efficient. If AI works, I can cut rates without causing inflation.' It's like a firefighter who's also an architect — he worries about fires but builds fireproof buildings.",
               "This thesis would be tested violently when oil spiked to $125 in April (inflation from energy, not demand — different ballgame). But in February, the Warsh put was alive and well.")]),
        "data-engineering": pillar("⚡⚡ Survey week",
            "The State of Data Engineering 2026 survey dropped — 82% use AI daily, 42% expect team growth. The defining stat of the year.",
            [E("2026-02-10", "State of DE Survey: 82% Use AI Daily",
               "Joe Reis's 2026 State of Data Engineering survey published full results. 1,101 respondents. The headline: 82% of data engineers use AI tools daily. 42% expect their team to grow. Top AI use cases: writing code, debugging, and data pipeline optimization.",
               "Imagine asking 100 truck drivers if they use GPS. 82 say 'every single day.' That's what happened in data engineering — AI went from novelty to necessity in 12 months.",
               "This single statistic changed how data platform teams budget, hire, and architect. If 82% of data engineers already use AI daily, the question isn't 'should we adopt AI?' but 'how do we make our pipelines AI-ready?'",
               links=[{"label": "State of DE 2026", "url": "https://practicaldata.community/"}]),
             E("2026-02-15", "Flink K8s Operator 1.14.0 Released",
               "The Flink Kubernetes Operator hit 1.14.0 with improved autoscaling, better checkpoint management, and enhanced monitoring. Streaming infrastructure continued its march toward production-grade operations.",
               "Like a car getting better suspension and brakes — the engine (Flink) was already great, but the operator makes it a smoother ride for operators.",
               "Flink's operator maturity was critical for the Lakestream paradigm: if you can't run Flink reliably on Kubernetes, the Debezium→Kafka→Flink→Iceberg stack doesn't work in production.")]),
    }),

    # ═══ W08 ═══
    W("2026-W08", "Feb 16 – Feb 22", pillars={
        "aml": pillar("🏛️ Quiet compliance week",
            "Quiet week in AML as FATF updates settled and the industry absorbed the grey list changes.",
            []),
        "markets": pillar("🏛️ Market structure week",
            "SEC extended Reg NMS compliance to November 2027, giving the industry more time to adapt to the 23/5 trading world.",
            [E("2026-02-19", "SEC Extends Reg NMS Compliance Deadline",
               "The SEC pushed the Reg NMS minimum pricing increment compliance deadline from 2026 to November 2027. The tick size reform — moving from $0.01 to $0.005 increments for highly liquid securities — needed more implementation time.",
               "Imagine telling a construction crew they have two extra years to build a bridge. They're relieved, but also wondering what's taking so long. The tick size reform is complex because it touches every trading system on Wall Street.",
               "This delay signaled that market structure reform was politically sensitive. The SEC wanted to get it right rather than rush — especially with 23/5 trading launching in parallel.")]),
        "data-engineering": pillar("⚡⚡ Apache Polaris Graduation",
            "Apache Polaris became a top-level ASF project — the vendor-neutral Iceberg catalog standard was born.",
            [E("2026-02-19", "Apache Polaris Graduates to TLP",
               "Apache Polaris — the Iceberg REST catalog originally acquired by Snowflake and open-sourced — graduated to a top-level ASF project. Unanimous board vote. 100+ contributors, 2,800+ PRs closed. The vendor-neutral catalog standard for lakehouses was now a real thing.",
               "Imagine a group of restaurants agreeing to use the same menu format so customers can order the same way at any restaurant. That's Polaris — it lets any Iceberg tool talk to any Iceberg catalog, regardless of vendor.",
               "This was the moment the 'format war' really ended. With a vendor-neutral catalog standard, Iceberg ecosystems could interoperate. Snowflake, Databricks, and everyone else could compete on features while sharing the storage layer.",
               links=[{"label": "Apache Polaris", "url": "https://polaris.apache.org/"}]),
             E("2026-02-20", "Iceberg vs Delta Decision Framework Published",
               "A comprehensive decision framework for choosing between Iceberg and Delta Lake was published. The verdict: both support ACID transactions. Choose Iceberg if you need multi-engine access (Spark, Flink, Trino, DuckDB). Choose Delta if you're deeply embedded in the Databricks ecosystem.",
               "Like choosing between Android and iPhone — both make calls, both run apps, but your choice depends on which ecosystem you're already invested in.",
               "This framework was necessary because the 'format war' narrative oversimplified reality. Most teams had clear ecosystem dependencies that made the choice for them.")]),
    }),

    # ═══ W09 ═══
    W("2026-W09", "Feb 23 – Mar 1", pillars={
        "aml": pillar("🏛️ Quiet compliance week",
            "AML compliance teams watched the oil crisis unfold — energy price spikes always correlate with trade-based money laundering risks.",
            []),
        "markets": pillar("⚡⚡⚡ Crisis week",
            "The biggest geopolitical event of 2026: the US-Iran conflict begins. Strait of Hormuz effectively closed. Oil prices spike toward $100+. Everything changes.",
            [E("2026-02-28", "US-Iran Conflict: Strait of Hormuz Closed",
               "The US-Iran conflict erupted. The Strait of Hormuz — the most important oil chokepoint in the world, carrying 20% of global seaborne crude — was effectively closed. Oil prices surged from ~$75 to over $100 in days. Brent would eventually hit $125 in April.",
               "Imagine someone blocking the only highway into a city where 20% of all food deliveries arrive. That's the Strait of Hormuz closing. Oil — the world's most important commodity — just lost its main shipping lane.",
               "This single event reshaped 2026. It drove inflation (Core PCE hit 4.1%), killed the rate-cut narrative, boosted energy stocks, crushed airlines and discretionary spending, and turned the S&P 500's earnings momentum from expansion to peak.",
               links=[{"label": "EIA Petroleum Status Report", "url": "https://www.eia.gov/"}]),
             E("2026-02-28", "Oil Spikes to Multi-Year Highs",
               "Brent crude surged from ~$75 to over $100/barrel. Gasoline prices jumped. The energy shock rippled through every sector: airlines sold off, consumer staples scrambled, and inflation expectations re-anchored higher.",
               "Oil at $100+ is like the price of bread suddenly tripling. Everything that uses oil — shipping, manufacturing, commuting, flying — gets more expensive. And every company that uses those things sees its margins squeezed.",
               "This wasn't just a market event — it was the defining macro event of 2026. Everything that followed (sticky inflation, rate hike expectations, sector rotation, JPMorgan's earnings warning) traced back to this moment.")]),
        "data-engineering": pillar("🔄 Quiet week",
            "Data engineering teams were preoccupied with the oil shock's impact on cloud costs (AWS, GCP, Azure all burn diesel for backup generators).",
            []),
    }),

    # ═══ W10 ═══
    W("2026-W10", "Mar 2 – Mar 8", pillars={
        "aml": pillar("🏛️ Quiet compliance week",
            "AML teams tracked the oil crisis for trade-based ML red flags.",
            []),
        "markets": pillar("📉 Oil crisis week 2",
            "Oil continued to spike. Reg NMS data revealed record equity market fragmentation. The macro picture darkened.",
            [E("2026-03-05", "Oil Continues Spike, Markets Adjust",
               "Brent held above $100. Markets started repricing for 'higher for longer' inflation. Energy stocks soared. Tech and discretionary stocks sold off as input cost fears mounted. The first hints of sector rotation appeared.",
               "When oil stays above $100 for two weeks, it's not a spike anymore — it's a new reality. Markets started behaving accordingly.",
               "The sector rotation that would define mid-2026 HRU? Small caps +22%, energy up, tech down — it all started here."),
             E("2026-03-07", "Record Equity Market Fragmentation",
               "SEC staff data showed off-exchange trading volumes at 51.9% (Nasdaq stocks) and 47% (NYSE stocks) — all-time highs. The SEC's Reg NMS rescission proposal was partially motivated by this fragmentation.",
               "Imagine a town where half the shopping happens outside the main marketplace. That's US equities — over half of all trades now happen in dark pools, internalizers, and off-exchange venues. The 'stock market' isn't one market anymore.",
               "This data point set the stage for the June Reg NMS rescission proposal — the most consequential equity market structure debate since 2005.")]),
        "data-engineering": pillar("⚡ Workflow engineering week",
            "The 'everyone's a workflow engineer' narrative emerged — orchestration becomes the universal data layer.",
            [E("2026-03-05", "Everyone's a Workflow Engineer Now",
               "Kestra (an orchestration platform) published '2026 Data Engineering Trends: Everyone's a Workflow Engineer Now.' The thesis: as AI handles more low-level coding, data engineers shift from writing ETL scripts to orchestrating workflows — designing the 'when' and 'why' of data movement rather than the 'how.'",
               "Imagine a chef who used to chop every vegetable by hand. Now she has a robotic knife (AI) that does the chopping. Her job shifts from chopping to deciding what to cook and when to serve it. That's the data engineer of 2026: orchestrator, not coder.",
               "This was the first clear articulation of the 'data engineer as orchestration designer' trend. By July, AI agents would be creating 80%+ of new databases on Databricks, making this prediction look prescient.")]),
    }),

    # ═══ W11 ═══
    W("2026-W11", "Mar 9 – Mar 15", pillars={
        "aml": pillar("🇪🇺 EU AML reform week",
            "EU AML Package Guide detailed 23 AMLA technical standards due by July 10. Moody's called AMLR the most significant EU AML reform in history.",
            [E("2026-03-12", "EU AML Package Guide Published",
               "A landmark guide detailed the 23 Regulatory Technical Standards (RTS), Implementing Technical Standards (ITS), and guidelines that EU financial institutions must comply with by July 10. Moody's published an independent review calling AMLR 'the most significant EU AML reform in history.'",
               "Imagine the EU is building a new house (AMLR), and the 23 technical standards are the blueprints for the plumbing, electrical, and foundation. If you're an EU bank, you need these blueprints to know where to run your pipes.",
               "The July 10 deadline created a compliance crunch for EU financial institutions. Those that started preparing in March would be fine. Those that waited? scrambling.")]),
        "markets": pillar("🏛️ Quiet week",
            "Markets caught their breath after the oil shock. The S&P 500 stabilized as traders assessed the damage.",
            []),
        "data-engineering": pillar("🔄 Quiet week",
            "Data engineering teams continued their Q1 projects.",
            []),
    }),

    # ═══ W12 ═══
    W("2026-W12", "Mar 16 – Mar 22", pillars={
        "aml": pillar("🏛️ Quiet compliance week",
            "AML teams continued tracking AMLA technical standard preparations.",
            []),
        "markets": pillar("🏦🏛️ Fed holds + inflation spike",
            "Fed held rates at 3.5-3.75%. PCE inflation hit 4.1% — driven entirely by the energy crisis. The rate-cut narrative died.",
            [E("2026-03-17", "Fed Holds Rates, PCE at 4.1%",
               "The March FOMC meeting held rates steady at 3.5-3.75%. The Fed's Monetary Policy Report showed PCE inflation at 4.1% — well above the 2% target. The culprit: energy prices surged after the Middle East conflict began. The rate-cut narrative officially died.",
               "Imagine you're trying to lose weight (lower inflation), but someone keeps bringing you donuts (energy prices). The Fed is saying 'we can't go off our diet while these donuts keep showing up.' Rate cuts won't happen until energy inflation subsides.",
               "This was the moment 'higher for longer' became the consensus view. Markets stopped pricing cuts and started pricing potential hikes. The implications for every asset class were profound."),
             E("2026-03-20", "CLARITY Act Stalls as Coinbase Withdraws Support",
               "Coinbase CEO Brian Armstrong withdrew support for the CLARITY Act over a provision banning passive stablecoin yield. The crypto bill's momentum stalled. Senator Lummis called it a 'big setback.'",
               "Imagine a bipartisan infrastructure bill that everyone loves — until the last minute, when someone adds a 'no bicycle lanes' clause that makes the cycling lobby walk out. That's CLARITY Act: consensus shattered by one controversial provision.",
               "The stablecoin yield ban would prove to be the CLARITY Act's most contentious issue. It would take until May to get the bill back on track.")]),
        "data-engineering": pillar("🔄 Quiet week",
            "Data engineering continued Q1 execution.",
            []),
    }),

    # ═══ W13 ═══
    W("2026-W13", "Mar 23 – Mar 29", pillars={
        "aml": pillar("🏛️ FinCEN whistleblower week",
            "FinCEN proposed a whistleblower reward rule — bringing AML enforcement into the 21st century with bounty hunting.",
            [E("2026-03-30", "FinCEN Proposes Whistleblower Rule",
               "FinCEN submitted a proposed rule to pay whistleblowers who report AML violations. This implements the Anti-Money Laundering Whistleblower Improvement Act and mirrors the SEC's wildly successful whistleblower program (which recovered over $1B from Dodd-Frank tips).",
               "Imagine putting up a 'WANTED' poster for money launderers with a cash reward. That's FinCEN's whistleblower rule — turning every bank employee into a potential informant with a financial incentive to report bad behavior.",
               "The SEC's whistleblower program has been its most effective enforcement tool. Expanding this to AML could dramatically increase detection of sophisticated laundering schemes that examiners miss.",
               links=[{"label": "FinCEN Whistleblower Proposed Rule", "url": "https://www.fincen.gov/"}]),
            ]),
        "markets": pillar("🔄 Quiet week",
            "Markets in wait-and-see mode after the PCE shock. Senate in recess.",
            []),
        "data-engineering": pillar("⚡ AI agents in production",
            "Flink Agents 0.2.1 preview release and AI-assisted pipeline development trends signal the agentic data infrastructure future.",
            [E("2026-03-26", "Flink Agents 0.2.1 Released",
               "Flink Agents — AI agents that can build, deploy, and monitor Flink pipelines — hit 0.2.1 preview. The agentic infrastructure movement was maturing. Meanwhile, 82% of DE survey respondents ranked 'writing code' as their #1 AI value use case.",
               "Imagine a junior developer who can write Flink jobs, deploy them, and fix them when they break — all without being asked. That's Flink Agents: AI that does the boring parts of stream processing so humans can focus on architecture.",
               "This was the leading edge of the 'AI agents create 80%+ of new databases' trend that would dominate by July.")]),
    }),

    # ═══ W14 ═══
    W("2026-W14", "Mar 30 – Apr 5", pillars={
        "aml": pillar("🏛️ FinCEN whistleblower week (cont.)",
            "Whistleblower rule submission marked the beginning of Q2's regulatory wave.",
            []),
        "markets": pillar("🏛️ Senate recess",
            "Senate in pro forma sessions. CLARITY Act frozen. Markets drifted on low volume.",
            []),
        "data-engineering": pillar("⚡⚡ Flink CDC 3.6.0",
            "Flink CDC 3.6.0 released — the biggest CDC release of 2026 with AI pipeline enhancements, new connectors, and better schema evolution.",
            [E("2026-03-30", "Flink CDC 3.6.0 Released",
               "Apache Flink CDC 3.6.0 dropped with: enhanced schema evolution for AI pipelines (auto-propagate to ML feature stores), new Oracle source connector, Apache Hudi sink, VARIANT type support, PARSE_JSON function, and JDK 11+ support. This was the most significant CDC release of 2026.",
               "Imagine a universal translator that not only converts languages in real-time but also updates the dictionary when it learns new words. Flink CDC 3.6.0 does that for databases — it captures changes and automatically evolves the schema for downstream ML systems.",
               "AI pipeline integration was the killer feature. ML feature stores could now automatically discover and ingest schema changes from source databases without manual intervention — a massive operational improvement.",
               links=[{"label": "Flink CDC 3.6.0 Release Notes", "url": "https://flink.apache.org/"}]),
            ]),
    }),

    # ═══ W15 ═══
    W("2026-W15", "Apr 6 – Apr 12", pillars={
        "aml": pillar("⚡⚡⚡ FinCEN proposes BSA overhaul",
            "The single most important AML week of 2026: FinCEN proposed fundamental BSA/AML reform — the biggest US AML overhaul since the PATRIOT Act.",
            [E("2026-04-10", "FinCEN Proposes Fundamental AML/CFT Reform",
               "FinCEN published a proposed rule in the Federal Register that would fundamentally restructure US AML/CFT requirements. The key changes: (1) risk-based resource allocation (focus on high-risk customers, reduce burden on low-risk), (2) effectiveness-based supervision (only 'significant failures' trigger enforcement), (3) explicit AI/ML encouragement, and (4) standardized risk assessment methodologies across all financial institutions.",
               "Imagine a police department that used to ticket every car going 1 mph over the limit (checklist compliance). The new policy: focus on catching drunk drivers (risk-based) and only pursue tickets for truly dangerous driving (effectiveness-based). Also, you can use radar guns (AI).",
               "This was the moment US AML regulation entered the 21st century. The old model — check every box equally — was replaced by a risk-intelligent framework that allocates resources where they matter most.",
               links=[{"label": "FinCEN Proposed Rule", "url": "https://www.fincen.gov/"}]),
            ]),
        "markets": pillar("🔄 Quiet week",
            "Markets digesting FinCEN reform and watching oil prices.",
            []),
        "data-engineering": pillar("⚡⚡⚡ LAKESTREAM LAUNCH",
            "StreamNative launched Lakestream architecture and Ursa for Kafka — the streaming-lakehouse unification product that would define 2026 data engineering.",
            [E("2026-04-07", "StreamNative Launches Lakestream + Ursa for Kafka",
               "StreamNative published the defining data engineering architecture of 2026: Lakestream — a single copy of data in Kafka topics that simultaneously serves real-time streaming and Iceberg table queries. Ursa for Kafka provides native Kafka on lakehouse storage with 95% cost reduction by eliminating separate streaming and batch storage.",
               "Imagine having two refrigerators — one for tonight's dinner, one for next month's meal prep. Lakestream says: use one refrigerator for both. Same food, same fridge, same cost. The 95% cost reduction comes from not buying a second fridge.",
               "This wasn't just a product launch — it was a paradigm shift. The batch/streaming duality that had plagued data architecture for a decade was finally resolved. One copy of data, two access patterns.",
               links=[{"label": "StreamNative Blog", "url": "https://streamnative.io/blog"}]),
            ]),
    }),

    # ═══ W16 ═══
    W("2026-W16", "Apr 13 – Apr 19", pillars={
        "aml": pillar("⚡⚡ GENIUS Act stablecoin rules + AMLA details",
            "FinCEN/OFAC proposed GENIUS Act rules for stablecoin issuers — first federal AML mandate for digital assets. AMLA Level 2 package detailed 23 technical standards.",
            [E("2026-04-16", "GENIUS Act Rules: Stablecoins get BSA Coverage",
               "FinCEN and OFAC proposed rules implementing the GENIUS Act — extending BSA customer identification program (CIP) requirements to stablecoin issuers. For the first time, digital asset issuers would have the same AML obligations as traditional banks.",
               "Imagine stablecoins have been operating like a taxi service that doesn't require driver's licenses or background checks. The GENIUS Act says: from now on, you need the same checks as a regular cab company. Passenger safety, meet the law.",
               "This closed the biggest regulatory gap in crypto AML. Stablecoins — the most widely used digital asset for payments — would now have the same KYC/AML obligations as the banks they compete with.",
               links=[{"label": "FinCEN GENIUS Act Rule", "url": "https://www.fincen.gov/"}]),
             E("2026-04-17", "AMLA Level 2 Package Detailed: 23 Standards Due Jul 10",
               "The EU's AMLA Level 2 package was analyzed in detail: 23 Regulatory Technical Standards, Implementing Technical Standards, and guidelines that EU financial institutions must implement by July 10, 2026. These cover everything from KYC procedures to cross-border information sharing to beneficial ownership registers.",
               "23 technical standards due in 3 months is like a university giving students 23 assignments due on the same day. EU compliance teams had a very busy Q2 ahead.",
               "The July 10 deadline was the single most important AML compliance date in Europe for 2026. Institutions that met it would be ahead of the regulatory curve; those that missed it would face supervisory scrutiny.")]),
        "markets": pillar("🏛️ Senate returns, CLARITY Act markup targeted",
            "Senate returned to full session. CLARITY Act Banking markup targeted for late April.",
            []),
        "data-engineering": pillar("⚡ Delta Lake 4.2.0",
            "Delta Lake 4.2.0 released with Unity Catalog Managed Table enhancements and streaming read support — format convergence continues.",
            [E("2026-04-16", "Delta Lake 4.2.0 with Unity Catalog Enhancements",
               "Delta Lake 4.2.0 released: Unity Catalog Managed Table enhancements, streaming read support (Delta tables can now be read as streaming sources), and improved format interoperability. The gap between Delta and Iceberg continued to narrow.",
               "Delta Lake is playing catch-up to Iceberg in the format war. Each release adds another feature that Iceberg already had. But for Databricks customers, each release also strengthens the integration with Unity Catalog — Databricks's moat.",
               "The format war narrative oversimplified: Iceberg won the industry standard battle, but Delta remained the best choice for Databricks-native teams. Both would coexist.")]),
    }),

    # ═══ W17 ═══
    W("2026-W17", "Apr 20 – Apr 26", pillars={
        "aml": pillar("🏛️ FinCEN reform analysis week",
            "BakerHostetler analyzed FinCEN's proposed rule: shift from 'checking boxes' to 'demonstrating results.'",
            [E("2026-04-22", "FinCEN Reform Analysis: 'Results, Not Paper'",
               "BakerHostetler published a detailed analysis of FinCEN's proposed AML/CFT program rule. The key insight: the rule shifts AML supervision from checking whether compliance boxes are ticked to evaluating whether the program actually prevents money laundering. 'Results, not paper.'",
               "Imagine a school that used to grade teachers on whether they took attendance and followed the lesson plan. The new system grades them on whether students actually learned. That's effectiveness-based supervision.",
               "This shift was profound. It meant compliance officers could stop pretending every customer was equally risky and focus on the genuine threats. It also meant more discretion — and more responsibility.")]),
        "markets": pillar("⚡⚡ Oil peaks + earnings warning",
            "Oil hit ~$125/barrel — the peak of the Hormuz crisis. JPMorgan warned earnings momentum was deteriorating. A double warning shot for markets.",
            [E("2026-04-22", "Oil Peaks at ~$125/barrel",
               "Brent crude hit approximately $125/barrel — the peak of the Hormuz crisis. US-Iran ceasefire talks collapsed. President Trump threatened to 'destroy Iranian bridges and power plants' if Hormuz ships were targeted. Energy markets were in full crisis mode.",
               "$125 oil is like filling up your car and realizing it costs as much as a nice dinner. For airlines, shipping companies, and manufacturers, it's devastating. For energy stock investors, it's Christmas.",
               "This was the high-water mark of the energy crisis. Oil would gradually decline after the June ceasefire, but the structural damage to inflation and earnings was done."),
             E("2026-04-23", "JPMorgan Warns: Earnings Momentum Deteriorating",
               "JPMorgan's equity strategy team published a note warning that S&P 500 earnings momentum was peaking. Key indicators: PPI-CPI spread declining (companies can't pass through costs), ISM Manufacturing Orders-to-Inventory ratio declining for 3 straight months. Defensive rotation was signaled.",
               "When JPMorgan — the biggest bank in America — says 'earnings are about to get worse,' markets listen. It's like your doctor telling you to stop eating junk food: you might not like it, but you should probably listen.",
               "This warning turned out to be prescient. By July, the S&P would be stuck at 7,499 resistance, unable to break through, and sector rotation would be in full swing.")]),
        "data-engineering": pillar("🔄 Quiet week",
            "Data engineering teams continued their Q2 projects.",
            []),
    }),

    # ═══ W18 ═══
    W("2026-W18", "Apr 27 – May 3", pillars={
        "aml": pillar("🏛️ Quiet week",
            "AML teams continued working on implementing the proposed FinCEN changes.",
            []),
        "markets": pillar("📉 Oil settles, CLARITY Act delayed",
            "Oil settled above $90 (the new floor). CLARITY Act markup slipped to May. Markets treaded water.",
            [E("2026-04-29", "Oil Settles Above $90, Markets Stable",
               "Brent crude settled above $90/barrel. The 'oil spike' was now 'the new normal.' Markets stabilized as traders accepted that $90+ oil was the baseline for the foreseeable future. CLARITY Act markup slipped to May due to the stablecoin yield dispute.",
               "When oil stays above $90 for two months, it stops being a 'spike' and becomes a 'price level.' The market adjusted: energy stocks became portfolio staples, discretionary stocks got squeezed, and everyone watched the Strait of Hormuz like hawks.",
               "The CLARITY Act delay was the first sign that crypto regulation would take longer than optimists hoped. The stablecoin yield debate would consume May.")]),
        "data-engineering": pillar("🔄 Quiet week",
            "Data engineering teams continued Q2 execution.",
            []),
    }),

    # ═══ W19 ═══
    W("2026-W19", "May 4 – May 10", pillars={
        "aml": pillar("🏛️ Quiet week",
            "AML teams tracked FinCEN comments and continued AMLA preparations.",
            []),
        "markets": pillar("🏛️ CLARITY Act markup",
            "CLARITY Act Senate Banking Committee markup began — the make-or-break moment for crypto regulation.",
            [E("2026-05-07", "CLARITY Act Banking Committee Markup Begins",
               "The Senate Banking Committee began marking up the CLARITY Act — the most comprehensive crypto regulation bill ever proposed. The stablecoin yield provision remained the biggest sticking point. Lobbyists swarmed Capitol Hill.",
               "A markup is like a committee editing a term paper together. Every senator gets to propose changes, debate them, and vote. The CLARITY Act markup was the most lobbied financial services bill of 2026.",
               "If the CLARITY Act passed committee, it would head to the full Senate. If it stalled in committee — as it nearly did in March — it might not get a floor vote at all.")]),
        "data-engineering": pillar("⚡ AI creates 80%+ of new databases",
            "AI agents now create 80%+ of new databases on Databricks — a stunning stat showing AI-native data infrastructure had arrived.",
            [E("2026-05-08", "AI Agents Create 80%+ of New Databases on Databricks",
               "Databricks disclosed that AI agents now autonomously create 80%+ of new databases on their platform. Data engineers shifted from building pipelines to reviewing and approving AI-generated ones. The 'orchestration designer' future had arrived.",
               "Imagine 80 out of every 100 new buildings in a city being designed and built by robots, with human architects just reviewing the blueprints and signing off. That's what happened to data engineering in 2026.",
               "This stat shocked the industry. We knew AI was coming for data engineering, but 80%+ autonomy happened faster than anyone predicted. The implications for jobs, skills, and platform architecture were enormous.")]),
    }),

    # ═══ W20 ═══
    W("2026-W20", "May 11 – May 17", pillars={
        "aml": pillar("🏛️ Quiet week",
            "AML teams tracked committee markup of CLARITY Act — the stablecoin AML provisions were part of the debate.",
            []),
        "markets": pillar("⚡⚡ Warsh becomes Fed Chair + CLARITY Act clears committee",
            "Two massive events: Kevin Warsh officially becomes Fed Chair (May 15). CLARITY Act passes Banking Committee 15-9 (May 14).",
            [E("2026-05-15", "Kevin Warsh Becomes Fed Chair",
               "Jerome Powell's term ended. Kevin Warsh was sworn in as the 16th Chair of the Federal Reserve. Markets immediately focused on his first FOMC meeting in June. Would he cut? Hold? Signal a new framework?",
               "The most powerful economic policy job in the world changed hands. Warsh — an inflation hawk who believes in AI productivity — now controlled the world's most important interest rate.",
               "Warsh's first moves would define his chairmanship: shorter FOMC statements, no forward guidance, and the formation of 5 task forces to review the Fed's framework. This was the beginning of a new monetary policy regime."),
             E("2026-05-14", "CLARITY Act Passes Banking Committee 15-9",
               "The Senate Banking Committee voted 15-9 to advance the CLARITY Act to the full Senate. The stablecoin yield issue was resolved with a compromise: stablecoin issuers can offer yields but must register as securities. The bill was one step from the floor vote.",
               "15-9 is a bipartisan vote in a divided committee. It meant the CLARITY Act had real momentum — not just Republican support but enough Democrats to cross the finish line.",
               "With committee passage, the CLARITY Act was placed on the Senate Legislative Calendar (Calendar No. 423) — eligible for full floor vote.")]),
        "data-engineering": pillar("⚡ Apache Polaris solidifies as catalog standard",
            "Apache Polaris emerged as the default catalog for Iceberg lakehouses — one standard to rule them all.",
            [E("2026-05-14", "Apache Polaris: The Catalog Standard for Lakehouses and AI",
               "Apache Polaris published its vision: 'The Catalog Standard for Lakehouses and AI.' With Snowflake, Databricks, and Google Cloud all supporting the Iceberg REST catalog protocol, Polaris became the default metadata layer for the entire lakehouse ecosystem.",
               "If Iceberg is the universal file format (like PDF), Polaris is the universal file manager (like Finder or Explorer). It doesn't matter what cloud or tool you use — Polaris can catalog your data.",
               "This was the final piece of the lakehouse puzzle: open format (Iceberg) + open catalog (Polaris) + open compute (Spark, Flink, Trino) = a truly open data ecosystem.")]),
    }),

    # ═══ W21 ═══
    W("2026-W21", "May 18 – May 24", pillars={
        "aml": pillar("🏛️ Quiet week",
            "AML teams focused on AMLA July 10 preparations.",
            []),
        "markets": pillar("📈 Warsh's first full week",
            "Warsh's first full week as Fed Chair. Markets priced in his hawkish-but-pro-productivity stance. Reg NMS reform debate intensified.",
            []),
        "data-engineering": pillar("⚡⚡⚡ ICBERG WINS THE FORMAT WAR",
            "Iceberg v3 GA on Snowflake, preview on Databricks. Iceberg v4 development begins. The format war is over — Iceberg is the industry standard.",
            [E("2026-05-20", "Iceberg v3 GA on Snowflake, Preview on Databricks",
               "Iceberg v3 went GA on Snowflake and entered preview on Databricks. This was the moment the format war ended: both major cloud data platforms now support Iceberg natively. Delta Lake conceded via UniForm (which provides Iceberg compatibility). The industry standard was settled.",
               "Imagine VHS vs. Betamax, Blu-ray vs. HD DVD, or iPhone vs. Android. Every format war ends when the market picks one. Iceberg won. Not by being clearly better in every dimension, but by being the most open and most widely supported.",
               "This had enormous implications: tool vendors could invest in Iceberg support without hedging, data teams could standardize on one format, and the ecosystem could focus on innovation rather than compatibility.",
               links=[{"label": "Apache Iceberg", "url": "https://iceberg.apache.org/"}]),
             E("2026-05-22", "Iceberg v4 Development Initiated",
               "The Iceberg community began the v4 development process: relative paths for cloud-agnostic table references, content statistics for query optimization, and enhanced metadata management. The standard was already moving to the next generation.",
               "No sooner had Iceberg won the format war than the community started building the next version. It's like the Olympic marathon winner immediately starting to train for the next race.",
               "Iceberg v4's relative paths feature was particularly important: it would allow Iceberg tables to be referenced in a cloud-agnostic way, further reducing vendor lock-in.")]),
    }),

    # ═══ W22 ═══
    W("2026-W22", "May 25 – May 31", pillars={
        "aml": pillar("🏛️ Fed AML reform alignment",
            "The Fed signaled alignment with FinCEN's effectiveness-based AML approach. Banking regulators coordinating on AML modernization.",
            [E("2026-05-27", "Fed Joins FinCEN in AML Reform Push",
               "The Federal Reserve Board signaled that its pending AML program reforms would align with FinCEN's April proposed rule. Key themes: risk-based resource allocation, effectiveness-based supervision, and AI/ML encouragement. The US banking regulators were coordinating on the most significant AML modernization in a generation.",
               "When the Fed and FinCEN agree on something, it's like the captain and first mate agreeing on the navigation route. Banks should pay attention: coordinated regulation means this reform is real.",
               "This set the stage for the July 7 Fed proposal — which would formalize these principles in a concrete rulemaking.")]),
        "markets": pillar("🏛️ Reg NMS reform debate",
            "House Market Structure Hearing on Reg NMS reform. Rule 611 (Order Protection Rule) under scrutiny. Record $1T single-day trading volume highlighted the need for modernized regulation.",
            [E("2026-05-27", "House Hearing: Reg NMS Reform Intensifies",
               "The House Financial Services Committee held a market structure hearing focusing on Reg NMS reform. Rule 611 — the Order Protection Rule (trade-through rule) — was the main target. Critics argued it was outdated in a world of 23/5 trading, sub-penny increments, and 51.9% off-exchange volume. US equity trading surpassed $1 trillion in a single day this week.",
               "Imagine a traffic law written in 2005 that says 'all cars must stop at every intersection.' In 2026, with self-driving cars and 23-hour traffic, that law is obsolete. That's Rule 611 — a 2005 regulation struggling with a 2026 market.",
               "The $1T single-day volume was a powerful data point: US equity markets were the largest, most active in history. Regulation designed for a smaller, slower market needed updating.")]),
        "data-engineering": pillar("🔄 Quiet week",
            "Data engineering teams absorbed the 'Iceberg won' news and began planning migration strategies.",
            []),
    }),

    # ═══ W23 ═══
    W("2026-W23", "Jun 1 – Jun 7", pillars={
        "aml": pillar("🏛️ Quiet week",
            "AML teams prepared for the July wave.",
            []),
        "markets": pillar("🏛️ CLARITY Act on Senate calendar",
            "CLARITY Act placed on Senate Legislative Calendar (Calendar No. 423) — eligible for floor vote. Crypto regulation was one step from becoming law.",
            [E("2026-06-01", "CLARITY Act Placed on Senate Calendar",
               "The CLARITY Act was placed on the Senate Legislative Calendar as Calendar No. 423. This means it was eligible for a full floor vote without additional committee action. The crypto industry held its breath.",
               "Getting on the Senate calendar is like a movie being 'coming soon' — it's not showing yet, but it could be scheduled any day. The CLARITY Act was one procedural step from a full Senate vote.",
               "The bill's fate now depended on Senate Majority Leader scheduling it for floor time. With the July 4 recess approaching, the window was narrowing.")]),
        "data-engineering": pillar("⚡ Google Cloud joins Iceberg ecosystem",
            "Google Cloud announced next-gen cross-cloud Lakehouse — AI-native, Iceberg-native, multi-cloud. All 3 major clouds now aligned on Iceberg.",
            [E("2026-06-03", "Google Cloud Announces Iceberg-Native Lakehouse",
               "Google Cloud unveiled its next-gen cross-cloud Lakehouse platform: AI-native (Vertex AI integration built-in), Iceberg-native (first-class Iceberg support, not a compatibility layer), and multi-cloud (can query data in AWS and Azure from GCP). With this, all 3 major clouds were Iceberg-native.",
               "With AWS, Azure, and GCP all supporting Iceberg natively, the table format became like the USB-C of data — one standard that works everywhere, regardless of the device (cloud) you plug into.",
               "This was the final seal on Iceberg's victory. When every cloud vendor supports the same open format, customers win: no lock-in, portable workloads, and a competitive market for compute tools.")]),
    }),

    # ═══ W24 ═══
    W("2026-W24", "Jun 8 – Jun 14", pillars={
        "aml": pillar("⚡⚡ FinCEN expands 314(b) to fraud",
            "FinCEN expanded Section 314(b) information sharing to include fraud — broadening the AML safe harbor beyond traditional money laundering.",
            [E("2026-06-10", "FinCEN 314(b) Expanded to Include Fraud",
               "FinCEN expanded the Section 314(b) information sharing safe harbor to cover fraud detection. Previously, 314(b) only protected institutions sharing information about money laundering and terrorist financing. Now, banks can share customer information about suspected fraud without legal liability.",
               "Imagine two neighbors who could only warn each other about burglars (money laundering). Now they can also warn each other about con artists (fraud). The more information sharing, the harder it is for criminals to hide.",
               "This was a practical, no-regrets reform: it costs nothing, requires no new systems, and immediately improves fraud detection across the financial system.")]),
        "markets": pillar("⚡⚡⚡ TRIPLE HEADER",
            "SEC proposes rescinding Reg NMS Rule 611. 0DTE hits 1/3 of all options volume. Retail options hit $6.8B daily. S&P concentration at record 40%.",
            [E("2026-06-11", "SEC Proposes Rescinding Reg NMS Rule 611",
               "The SEC proposed rescinding Reg NMS Rule 611 (Trade-Through Rule) and Rule 610(e) (locked/crossed markets) — the most significant equity market structure deregulation since the 2005 adoption of Reg NMS itself. The comment period was open for 60 days.",
               "Imagine the government saying 'the rule that says you can't trade through a better price is now optional.' That's what rescinding Rule 611 does — it removes the requirement that orders must be routed to the venue showing the best price.",
               "This was the most consequential market structure proposal since decimalization. If implemented, it would fundamentally change how US equities are traded, who gets the order flow, and how markets ensure best execution.",
               links=[{"label": "SEC Proposed Rule", "url": "https://www.sec.gov/"}]),
             E("2026-06-10", "0DTE Now 1/3 of All Options Volume",
               "Citadel Securities reported that zero-days-to-expiry options now account for 1/3 of all listed options volume. Retail options premium reached $6.8B daily. These are structural, permanent shifts in the options market — not a temporary trend.",
               "0DTE options are like same-day delivery for financial bets. You can bet on where the S&P 500 will be by 4 PM today. They're now 1/3 of all options trading — which is like 1/3 of all packages being same-day delivery.",
               "This changes everything about market structure: intraday volatility is amplified, market-making risk is concentrated in shorter timeframes, and the VIX is less reliable as a tail-risk hedge."),
             E("2026-06-13", "S&P 500 Concentration: Top 10 = ~40% of Index",
               "The top 10 stocks in the S&P 500 reached approximately 40% of total index weight — the highest concentration in history. Apple, Microsoft, Nvidia, Amazon, Meta, Alphabet (×2), Berkshire Hathaway, Tesla. Passive investors now had massive single-stock risk.",
               "The S&P 500 is supposed to be a 'diversified' index. But 40% of your money is in just 10 companies. It's like ordering a 'sampler platter' and getting 40% french fries.",
               "This concentration risk was a ticking time bomb. If the top 10 stocks corrected, the entire index would fall — even if the other 490 companies were fine.")]),
        "data-engineering": pillar("🔄 Quiet week",
            "Data engineering teams continued their Q2 projects, eyes on the Reg NMS proposal's implications for market data pipelines.",
            []),
    }),

    # ═══ W25 ═══
    W("2026-W25", "Jun 15 – Jun 21", pillars={
        "aml": pillar("⚡⚡ GENIUS Act CIP rule detailed",
            "FinCEN and agencies proposed the GENIUS Act Customer Identification Program rule — stablecoin issuers must now know their customers.",
            [E("2026-06-18", "GENIUS Act CIP Rule: Know Your Stablecoin Customer",
               "FinCEN, along with other federal agencies, proposed the Customer Identification Program (CIP) rule implementing the GENIUS Act. Stablecoin issuers would be treated like banks for KYC purposes: verify customer identity, maintain records, and check against sanctions lists.",
               "Stablecoins have been like cash — anonymous and hard to trace. The GENIUS Act says 'from now on, using a stablecoin is like using a debit card — you need an account, and the bank knows who you are.'",
               "This completed the 'stablecoin AML trifecta': issuer CIP rules, travel rule compliance, and BSA program requirements. Digital assets were now fully in the AML framework.")]),
        "markets": pillar("⚡⚡⚡ Warsh's first FOMC + Iran ceasefire + Reg NMS proposal",
            "Kevin Warsh's first FOMC: shorter statement, no forward guidance, 5 task forces. Iran MOU signed — oil collapses from $125 to $70-85. Reg NMS proposal published in Federal Register.",
            [E("2026-06-17", "Warsh's First FOMC: No Forward Guidance, 5 Task Forces",
               "Kevin Warsh chaired his first FOMC meeting. The statement was notably shorter (removed the 'patient' language and forward guidance entirely). The Fed formed 5 task forces to review monetary policy framework, balance sheet, payments, climate, and AI. Rates stayed at 3.5-3.75%. Markets interpreted: Warsh is a hawk who wants flexibility.",
               "Warsh's first statement was like a new CEO's first memo: short, direct, and signaling 'we're going to do things differently here.' The removal of forward guidance was the biggest change — markets would now have to guess what the Fed would do next.",
               "This was the beginning of the 'Warsh regime': less communication, more flexibility, and a focus on framework review over immediate action."),
             E("2026-06-17", "US and Iran Sign MOU: Hormuz Reopens, Oil Crashes",
               "The US and Iran signed a Memorandum of Understanding ending the conflict. The Strait of Hormuz reopened. Oil prices collapsed from ~$125 to $70-85/barrel in days. The biggest oil spike in decades was over.",
               "When the Strait of Hormuz reopened, it was like unblocking a highway after a 4-month traffic jam. The oil that was stuck could flow again, and prices plummeted.",
               "The oil collapse was deflationary — exactly what the Fed needed to see. But the geopolitical risk premium didn't fully disappear: oil would remain volatile in the $70-95 range through July."),
             E("2026-06-17", "SEC's Reg NMS Proposal Published in Federal Register",
               "The SEC's proposal to rescind Reg NMS Rules 611 and 610(e) was published in the Federal Register, opening a 60-day comment period. The formal rulemaking process began.",
               "Publishing in the Federal Register is like a restaurant posting its new menu. Everyone can see what's changing, and they have 60 days to send feedback before the kitchen starts cooking.")]),
        "data-engineering": pillar("⚡⚡ Flink 2.3.0 with Native S3 FS",
            "Apache Flink 2.3.0 released: Native S3 FileSystem, changelog SQL operators, materialized table refresh — the biggest Flink release of 2026.",
            [E("2026-06-25", "Flink 2.3.0: Native S3 FileSystem, Changelog Operators",
               "Apache Flink 2.3.0 released with: Native S3 FileSystem (no Hadoop dependency needed!), FROM_CHANGELOG/TO_CHANGELOG SQL operators for streaming CDC data, materialized table refresh strategies, and 15 FLIPs (Flink Improvement Proposals). This was the most significant Flink release of the year.",
               "Before Flink 2.3.0, reading from S3 required a heavy Hadoop dependency. Now Flink can talk to S3 directly — like removing the middleman from a conversation. The changelog operators handle the 'before and after' of database changes natively in SQL.",
               "The Native S3 FS was a big deal for cloud-native streaming: simpler deployments, smaller container images, and better performance for S3-based lakehouse architectures.")]),
    }),

    # ═══ W26 ═══
    W("2026-W26", "Jun 22 – Jun 28", pillars={
        "aml": pillar("🙌 Enforcement showcase",
            "FinCEN Law Enforcement Awards recognized 7 cases demonstrating effective use of BSA data.",
            [E("2026-06-22", "FinCEN Law Enforcement Awards: BSA Data Works",
               "FinCEN recognized 7 law enforcement cases where BSA data was instrumental in investigations. The message: the AML framework, when used effectively, produces real results. Cases included drug trafficking, fraud, and sanctions evasion.",
               "Like a police department highlighting 7 cases where neighborhood watch tips solved crimes. The message: 'your reports matter — keep filing them.'",
               "This was a morale boost for compliance teams amid the regulatory churn. Their work — filing SARs, maintaining records — was making a difference.")]),
        "markets": pillar("🏛️ CBDC banned through 2030",
            "The 21st Century ROAD to Housing Act included a provision banning the Fed from issuing a digital dollar through 2030. The US firmly rejected CBDCs.",
            [E("2026-06-24", "CBDC Ban Signed into Law Through 2030",
               "President Trump signed the 21st Century ROAD to Housing Act, which included a provision banning the Federal Reserve from issuing a central bank digital currency (CBDC) through 2030. The US took the most anti-CBDC stance of any major economy.",
               "While China's digital yuan, Europe's digital euro, and dozens of other CBDCs advance, the US said 'no thanks, we'll keep using paper dollars and bank deposits.' It's like the world is switching to smartphones, and the US decided to keep using flip phones — for now.",
               "This had implications for financial inclusion, cross-border payments, and sanctions enforcement. Without a CBDC, the US relied on the existing banking system for all digital payments and sanctions compliance.")]),
        "data-engineering": pillar("⚡ Open Lakehouse report confirms Iceberg standard",
            "Industry report: 'Open Data Lakehouse in 2026' confirmed Iceberg as the de facto standard, format war over.",
            [E("2026-06-25", "Open Data Lakehouse Report: Iceberg is the Standard",
               "The 'Open Data Lakehouse in 2026' report confirmed what everyone suspected: Iceberg won the format war. Delta Lake and Hudi were viable alternatives for specific use cases, but Iceberg was the industry standard. The report also highlighted the convergence of streaming and batch on the lakehouse.",
               "This was the official 'yearbook' for data engineering — declaring Iceberg 'most likely to succeed' in the format class. The debate was over.",
               "The report's streaming-lakehouse convergence theme was validated almost immediately by StreamNative's Lakestream architecture validation in July.")]),
    }),

    # ═══ W27 ═══
    W("2026-W27", "Jun 29 – Jul 5", pillars={
        "aml": pillar("⏰ AMLA July 10 deadline countdown",
            "The AMLA July 10 technical standards deadline loomed. EU financial institutions rushed final preparations. Also: Fed Monetary Policy Report showed 4.1% PCE inflation.",
            [E("2026-06-30", "AMLA Deadline 10 Days Away: EU Compliance Sprint",
               "With the July 10 deadline approaching, EU financial institutions entered a final compliance sprint. The 23 RTS, ITS, and guidelines covered everything from KYC procedures to cross-border information sharing. Firms that weren't ready faced AMLA supervisory scrutiny.",
               "Imagine 23 term papers due on the same day, and you've known about them for months but the deadline is suddenly 10 days away. That's every EU compliance team in late June 2026.",
               "The July 10 deadline was the single biggest AML compliance event in Europe for 2026. It marked the transition from the old directive-based regime (AMLD) to the new regulation-based regime (AMLR).")]),
        "markets": pillar("🔄 Oil volatility continues",
            "Oil briefly fell to ~$71 on peace hopes, but the Hormuz ceasefire was fragile. Markets maintained elevated uncertainty premiums.",
            []),
        "data-engineering": pillar("🔄 Quiet week",
            "Data engineering teams prepared for the July technology news cycle.",
            []),
    }),

    # ═══ W28 ═══
    W("2026-W28", "Jul 6 – Jul 12", pillars={
        "aml": pillar("⚡⚡⚡ SUPERWEEK",
            "AMLA publishes first ITS for direct supervision. EU AMLR core framework applies. Countries transpose AMLD6. Fed proposes AML program reforms. THE biggest AML week of 2026.",
            [E("2026-07-10", "AMLA Publishes First ITS for Direct Supervision",
               "The EU Anti-Money Laundering Authority published its first Implementing Technical Standards, establishing Joint Supervisory Teams and beginning the selection process for cross-border entities that would be directly supervised by AMLA starting 2028. This was the most significant supranational AML development in history.",
               "AMLA is like an EU-wide FBI for money laundering. For the first time, a single European agency will directly supervise the biggest, riskiest financial institutions — rather than relying on 27 different national regulators.",
               "This was the culmination of years of EU AML reform. The operational launch of AMLA direct supervision changes the European AML landscape forever.",
               links=[{"label": "AMLA", "url": "https://www.AMLA.europa.eu/"}]),
             E("2026-07-10", "EU AMLR Core Framework Applies + AMLD6 Transposition",
               "The EU AML Regulation (AMLR) core framework officially applied — a single rulebook replacing the patchwork of national implementations. Simultaneously, France, Germany, Netherlands, and Spain transposed AMLD6 into national law.",
               "Before AMLR, EU AML rules were like 27 different rulebooks for the same game. Now there's one rulebook that everyone follows. AMLD6 is the enforcement directive — the 'if you break the rules, this is what happens' part.",
               "The combination of AMLR (single rulebook) + AMLA (single supervisor) + AMLD6 (enforcement) creates a truly unified EU AML framework for the first time."),
             E("2026-07-07", "Fed Proposes AML Program Reforms",
               "The Federal Reserve Board proposed amendments to AML program requirements for state member banks, bank holding companies, and foreign banking organizations. Key changes: risk-based resource allocation, effectiveness-based supervision, board approval requirement, US-based compliance officer for foreign banks, and explicit AI/ML encouragement.",
               "The Fed said: 'Stop checking every box equally. Focus your compliance energy where the real risk is. And by the way, AI is welcome here.' This was the biggest US AML reform since the PATRIOT Act of 2001.",
               "Together with FinCEN's April proposed rule and the GENIUS Act, this created the most significant US AML transformation in a generation. The three-legged stool: risk-based allocation, effectiveness-based supervision, and technology encouragement.",
               links=[{"label": "Fed Proposed Rule", "url": "https://www.federalreserve.gov/"}]),
            ]),
        "markets": pillar("⚡⚡ Hormuz crisis reignites",
            "Iran attacked 3 commercial vessels in the Strait of Hormuz (Jul 7). US retaliatory strikes (Jul 8). Trump declared the ceasefire over. Oil rebounded from $71 to $78+.",
            [E("2026-07-07", "Hormuz Crisis Reignites: Oil Surges from $71 to $78+",
               "The US-Iran ceasefire collapsed. Iran attacked 3 commercial vessels in the Strait of Hormuz. The US launched retaliatory strikes. President Trump declared the ceasefire 'over.' Oil surged from ~$71 to $78+ in 48 hours. The geopolitical premium returned with a vengeance.",
               "The brief peace was like a cease-fire that lasted just long enough for everyone to catch their breath before the next punch. Oil traders who thought the crisis was over got a brutal reminder: Hormuz is never 'safe.'",
               "This renewed volatility set the stage for the July 22 oil surge to $95+. The Hormuz crisis had a playbook now: ceasefire → spike → collapse → ceasefire collapse → spike again.")]),
        "data-engineering": pillar("⚡⚡ Iceberg named industry standard + Lakestream validated",
            "TechTarget: Iceberg named 'de facto industry standard.' Delta Lake concedes via UniForm. StreamNative publishes Lakestream architecture paper with 95% cost reduction.",
            [E("2026-07-09", "Iceberg Named 'De Facto Industry Standard'",
               "TechTarget published a landmark analysis declaring Apache Iceberg the 'de facto industry standard' for lakehouse table formats. The article noted that Delta Lake had effectively conceded via UniForm (which provides Iceberg compatibility). The format war was officially, finally over.",
               "Remember the Coke vs. Pepsi taste tests? Imagine Pepsi waving a white flag and saying 'our drink can now be served in Coke bottles.' That's Delta Lake adopting Iceberg compatibility — the format war ended with a merger, not a knockout.",
               "This declaration had real consequences: tool vendors stopped hedging bets, data teams standardized on Iceberg, and the community focused on v4 features rather than competition."),
             E("2026-07-10", "Lakestream Architecture Validated: 95% Cost Reduction",
               "StreamNative published the full Lakestream architecture paper, demonstrating how one copy of data in Kafka topics simultaneously serves real-time streaming and Iceberg table queries. Independent validation showed 95% cost reduction and simplified operations.",
               "The first build (April) said Lakestream was possible. The July paper proved it worked. Independent validation turned a vision into an architecture pattern that every data platform team could adopt.",
               "This was the third pillar of the 'streaming-lakehouse unification' trend. First Flink CDC 3.6.0 (March), then Lakestream launch (April), now validated architecture (July). The pattern was established.")]),
    }),

    # ═══ W29 ═══
    W("2026-W29", "Jul 13 – Jul 19", pillars={
        "aml": pillar("🏛️ Post-AMLA assessment week",
            "Compliance teams assessed the impact of the July 10 AMLA deadline and the Fed's proposed reforms.",
            []),
        "markets": pillar("📈 Q2 earnings season opens with 88% beat rate",
            "Q2 2026 earnings season opened with an astonishing 88% beat rate — the strongest since 2021. 16.4% above estimates, 23.3% YoY growth. The 'last good earnings season' before JPMorgan's warning.",

            [E("2026-07-17", "Q2 Earnings: 88% Beat Rate, 23.3% YoY Growth",
               "FactSet reported Q2 2026 earnings results: 88% of S&P 500 companies beat earnings estimates (strongest since 2021), average surprise was +16.4% above estimates, earnings growth was +23.3% YoY. The Mag 7 (Apple, Microsoft, Nvidia, Amazon, Meta, Alphabet, Tesla) remained the top contributors to index-level growth.",
               "88% of companies beating estimates is like 9 out of 10 students acing a test. The 'test' (earnings expectations) was set by analysts who didn't believe the earnings momentum would last. Turns out, it did — just barely.",
               "This would likely be remembered as the peak of the cycle. JPMorgan warned on July 23 that the 'earnings fuel' was running out. The Q2 print was the final 'good news' before the rotation.")]),
        "data-engineering": pillar("🔄 Quiet week",
            "Data engineering teams continued Q3 projects.",
            []),
    }),

    # ═══ W30 ═══
    W("2026-W30", "Jul 20 – Jul 26", pillars={
        "aml": pillar("🏛️ FinCEN enforcement focus",
            "FinCEN extended comment period for Huione Group rule targeting pig-butchering scam networks.",
            [E("2026-07-22", "FinCEN Targets Pig-Butchering Scams",
               "FinCEN extended the comment period for a proposed rule targeting Huione Group — a Cambodian conglomerate linked to pig-butchering scam networks. These sophisticated romance/investment scams have bilked victims of billions and represent a new frontier in financial crime.",
               "Pig-butchering scams are like online romance meets investment fraud: criminals build trust over weeks, then convince victims to 'invest' in fake platforms. The name comes from 'fattening the pig before slaughter.' FinCEN was blocking the slaughterhouse.",
               "This was the leading edge of AML enforcement against tech-enabled fraud networks. The scams were evolving faster than traditional AML tools could track.")]),
        "markets": pillar("⚡⚡⚡ CRISIS WEEK",
            "CLARITY Act updated with presidential crypto ban. Oil surges past $95. JPMorgan warns earnings fuel running out. The worst week for markets since the Hormuz crisis began.",
            [E("2026-07-22", "CLARITY Act v2: President Banned from Issuing Crypto",
               "Senate Republicans unveiled revised CLARITY Act text banning the president, vice president, Congress members, and federal judges from issuing or profiting from cryptocurrency. Bitcoin fell 31% YTD on regulatory uncertainty. The bill was the most consequential crypto regulation debate of 2026.",
               "Imagine a law that says 'the President can't start a cryptocurrency.' That's not hypothetical — that's the CLARITY Act. It's Congress saying 'digital money is powerful enough that even the most powerful person in the world shouldn't control it.'",
               "The presidential crypto ban was unprecedented: no other country had proposed such a rule. It reflected a deep bipartisan distrust of executive branch involvement in digital assets."),
             E("2026-07-23", "Oil Surges Past $95/barrel",
               "Brent crude surged past $95/barrel — a 6-week high. The 4-day dollar gain was the largest since April 29. Gasoline crossed back above $4/gallon. The Hormuz crisis had a new chapter.",
               "Oil at $95 means everything gets more expensive: shipping, manufacturing, commuting, flying. For the average American, $4 gasoline is the most visible inflation signal there is. For markets, $95 oil means the Fed can't cut rates.",
               "The oil shock compounded the earnings pressure: higher input costs + sticky inflation + no rate cuts = a toxic mix for risk assets."),
             E("2026-07-23", "JPMorgan: 'Earnings Fuel Running Out'",
               "JPMorgan's equity strategy team published a stark warning: the PPI-CPI spread has peaked and is declining (companies can't pass through costs), the ISM Manufacturing Orders-to-Inventory ratio has declined for 3 consecutive months (weakening demand), and the market should rotate toward defensive assets. The S&P was stuck at 7,499 resistance.",
               "JPMorgan is saying the earnings party is over. The DJ is packing up, the lights are coming on, and it's time to call a taxi (buy defensive stocks). The PPI-CPI spread is the 'how much are input costs eating into profits' meter — and it's flashing red.",
               "This warning crystallized the macro narrative for H2 2026: earnings peaking, oil elevated, Fed unable to cut, and defensive rotation the only sane strategy.")]),
        "data-engineering": pillar("🔄 Quiet week",
            "Data engineering teams focused on Lakestream adoption and Iceberg migration planning.",
            []),
    }),
]

# Write the file
OUT.parent.mkdir(parents=True, exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    json.dump({"weeks": weeks}, f, indent=2, ensure_ascii=False)

print(f"Written {len(weeks)} weeks to {OUT}")
# Count events per week
total_events = 0
for w in weeks:
    for p, data in w.get("pillars", {}).items():
        total_events += len(data.get("events", []))
print(f"Total events across all weeks: {total_events}")
# Count events per pillar
pillar_counts = {}
for w in weeks:
    for p, data in w.get("pillars", {}).items():
        pillar_counts[p] = pillar_counts.get(p, 0) + len(data.get("events", []))
for p, c in sorted(pillar_counts.items()):
    print(f"  {p}: {c} events")
